### PR TITLE
 Add Feature: Download Report File

### PR DESCRIPTION
**Pull request by taojy123**
Export all statistics data to a `html` file, and you can **download** it to your computer.

As follows:

download

report

### CODE REVIEW

**Comment by cyberw** [comment]
Hmm... you're adding an entirely new greenlet for this feature. Would it be possible to do this outside locust core?

I'm not sure the maintenance will be worth it...

**Comment by taojy123** [comment]
Sorry, I didn't get the point.
Is it that `stats_history_greenlet` is not a good way to do this?
How can I improve the code, Thankyou~

**Comment by cyberw** [comment]
My main issue is that I dont use the web UI, so I usually be bothered with these things :)

I'm +/- 0 for this. It looks nice enough. If any of the other maintainers wake up and want to merge this then I'm fine with it.

**Comment by taojy123** [comment]
oh, haha~ I see, thanks 😁

**Comment by cyberw** [comment]
I couldnt help myself and had a look at the report. It looks great.

If you just fix the test fail that appeared I will merge!

**Comment by taojy123** [comment]
I just fixed the conflict, but the coverage decrease 1.18%  😅
I'll try to add some testcases.

**Comment by cyberw** [comment]
Ignore the coverage changes, it is a little flaky...

**Comment by taojy123** [comment]
I modify the test cases, buy `Codecov Report` hasn't changed at all.
I run `python setup.py test` on my computer, all 316 test cases were successful.
What should I do now?

**Comment by taojy123** [comment]
done! 😄

**Comment by cyberw** [comment]
thx!

**Comment by cyberw** [comment]
Hmm... I get warnings about this file descriptor never being closed. Can you fix it?

/home/travis/build/locustio/locust/locust/web.py:217: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/travis/build/locustio/locust/locust/static/jquery-1.11.3.min.js' mode='r' encoding='utf8'>

**Comment by taojy123** [comment]
Ok!
It would be better to replace 
```
with open(path, encoding='utf8') as f:
    content = f.read()
```
with
```
content = open(path, encoding='utf8').read()
```
in `stats_report` function.

**Comment by cyberw** [comment]
Yes. But the opposite of what you just said. So I hope that was what you meant :)

**Comment by cyberw** [comment]
I accidentally pushed a commit to your master (taojy123/master) Sorry about that 😳

**Comment by taojy123** [comment]
Ha~ don't worry
And I committed the change to taojy123/locust, 
https://github.com/taojy123/locust/commit/a1e6e658fd71cca17c4904c549db0e4d06e0a943

**Pull request merged**
