### PR TITLE
Fix frontend bugs.

### PR DESCRIPTION
**Pull request by omittones**
Console error while sorting the table (report is undefined). Extracted code for rendering the table.

### CODE REVIEW

**Comment by cyberw** [comment]
Hi @omittones ! Is this still relevant?

**Comment by omittones** [comment]
No idea, haven't used locust in a while. Will see tomorrow and close it if
it's not.

**Comment by omittones** [comment]
> Hi @omittones ! Is this still relevant?

Hey, I merged with master and this is still relevant. It includes a fix for error happening on frontend, and minor refactoring.

**Comment by cyberw** [comment]
Thanks!

**Pull request merged**
