### PR TITLE
Put dependencies/package information in pyproject.toml instead of setup.cfg (PEP621)

### PR DESCRIPTION
**Pull request by JE-Chen**
Add pep621_pyproject.toml

* This TOML file complies with PEP517 & PEP518 & PEP621

This link is for the PYPI package generated by this TOML file.

* https://pypi.org/project/locust-je-test-pep621/2.15.2.dev8/

I don't want to overwrite old pyproject.toml so i call this file pep621_pyproject.toml

PEP621
* https://peps.python.org/pep-0621/

### CODE REVIEW

**Comment by cyberw** [comment]
Nice. But go ahead and add it to pyproject.toml, otherwise it will not be tested before merging etc. We definitely dont want to have both at the same time. Is this compatible with Python 3.7 btw?

You'll need to merge this with latest master to get the build working (because of this https://github.com/locustio/locust/pull/2337)

**Comment by JE-Chen** [comment]
> Is this compatible with Python 3.7 btw?
Sure, but we need upgrade build & setuptools (setuptools>=61) first

**Comment by cyberw** [comment]
> PEP621 allows pyproject.toml to generate the package on its own, but CI/CD requires setup.cfg so I didn't delete it.

Hm. If we'd have to maintain duplicate dependencies in setup.cfg I dont think this is worth it.

**Comment by JE-Chen** [comment]
Look like we don't need  setup.cfg & setup.py anymore

**Comment by cyberw** [comment]
That just ensures pip cache uniqueness, an optimization for faster (repeated) builds. I think you can replace 'setup.cfg' with 'pyproject.toml'

**Comment by cyberw** [comment]
Makefile needs to be adjusted too, as this doesnt work anymore:

```
build:
	rm -f dist/* && python3 setup.py sdist bdist_wheel
```

**Comment by cyberw** [comment]
While you are at it, you can nuke `examples/vagrant/vagrant.sh`. 

It contains a reference to setup.py which will stop working now. And the file hasnt been updated in 11 (!) years :)

**Comment by cyberw** [comment]
Hmm...
image

**Comment by JE-Chen** [comment]
We need "pip install --upgrade build" first

**Comment by cyberw** [comment]
> We need "pip install --upgrade build" first

Yea, I was in a virtualenv and forgot to install it. Oops. Do you wanna remove vagrant.sh or should I?

**Comment by cyberw** [comment]
Good stuff, thanks!

**Pull request merged**
