### PR TITLE
fix(dispatch): UserClasses weight distribution with gcd

### LINKED ISSUE #2662: Wrong distribution of virtual users by user classes
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

Hi, thanks for the awesome project. I came across the behavior of locust that is unclear to me. 
When I create two user classes `TestUser1` and `TestUser2` with weights of 20 and 25 respectively, the actual distribution shows that 23 and 22 virtual users were created respectively. The sum of 45 is identical, but it is the distribution, I consider, that is being performed incorrectly. I think there should be 20 VUsers for `TestUser1` and 25 for `TestUser2`.

[Documentation](https://docs.locust.io/en/stable/writing-a-locustfile.html#weight-and-fixed-count-attributes) says:
> If you wish to simulate more users of a certain type you can set a weight attribute on those classes.

Locust logs:
```bash
[2024-04-01 20:43:46,470] cab-wsm-0023164/INFO/locust.main: Starting web interface at http://0.0.0.0:8089
[2024-04-01 20:43:46,483] cab-wsm-0023164/INFO/locust.main: Starting Locust 2.24.1
[2024-04-01 20:43:50,643] cab-wsm-0023164/INFO/locust.runners: Ramping to 45 users at a rate of 50.00 per second
[2024-04-01 20:43:50,643] cab-wsm-0023164/DEBUG/locust.runners: Ramping to {"TestUser1": 23, "TestUser2": 22} (45 total users)
[2024-04-01 20:43:50,644] cab-wsm-0023164/DEBUG/locust.runners: Spawning additional {"TestUser1": 23, "TestUser2": 22} ({"TestUser1": 0, "TestUser2": 0} already running)...
[2024-04-01 20:43:50,645] cab-wsm-0023164/DEBUG/locust.runners: 10 users spawned
[2024-04-01 20:43:50,646] cab-wsm-0023164/DEBUG/locust.runners: 20 users spawned
[2024-04-01 20:43:50,646] cab-wsm-0023164/DEBUG/locust.runners: 23 users spawned
[2024-04-01 20:43:50,646] cab-wsm-0023164/DEBUG/locust.runners: All users of class TestUser1 spawned
[2024-04-01 20:43:50,647] cab-wsm-0023164/DEBUG/locust.runners: 33 users spawned
[2024-04-01 20:43:50,648] cab-wsm-0023164/DEBUG/locust.runners: 43 users spawned
[2024-04-01 20:43:50,648] cab-wsm-0023164/DEBUG/locust.runners: 45 users spawned
[2024-04-01 20:43:50,648] cab-wsm-0023164/DEBUG/locust.runners: All users of class TestUser2 spawned
[2024-04-01 20:43:50,648] cab-wsm-0023164/DEBUG/locust.runners: 0 users have been stopped, 45 still running
[2024-04-01 20:43:50,648] cab-wsm-0023164/INFO/locust.runners: All users spawned: {"TestUser1": 23, "TestUser2": 22} (45 total users)
```

### Command line

locust --host http://localhost:5000 --users 45 --spawn-rate 50 --loglevel "DEBUG"

### Locustfile contents

```python3
from locust import FastHttpUser, constant_pacing, task


class TestUser1(FastHttpUser):
    wait_time = constant_pacing(7200)
    weight = 20

    @task
    def hello_world(self):
        self.client.get("http://localhost:5000/1")


class TestUser2(FastHttpUser):
    wait_time = constant_pacing(7200)
    weight = 25

    @task
    def hello_world2(self):
        self.client.get("http://localhost:5000/2")
```

### Python version

3.11.6

### Locust version

2.24.1

### Operating system

MacOS 13.6.4

### PR DESCRIPTION
**Pull request by llirrikk**
Fixes #2662

### CODE REVIEW

**Comment by cyberw** [comment]
Awesome. Can I ask that you add a unit test that would fail with the old implementation?

**Comment by cyberw** [comment]
Tests seem to hang on python 3.8. That’s really weird..

**Comment by llirrikk** [comment]
I fixed the hanging tests in python 3.8. The reason turned out to be that the prototype of the function "math.gcd" was changed in version 3.9. As a result, support is now provided starting from version 3.5. Why exactly "actions" hang and not throw an exception is a good question.
I'll add a commit with tests soon, as you asked

**Comment by cyberw** [comment]
Nice. Support for python 3.8 is deprecated anyway (and it python 3.8 is eol in october, after which we’ll probably stop supporting it), but it is nice that we dont have to kill it right away :)

**Comment by llirrikk** [comment]
It looks done to me

**Comment by llirrikk** [comment]
Added unit tests

**Pull request merged**
