### PR TITLE
Fix: Validate headless and host options

### LINKED ISSUE #2575: Locust spams error if Host is invalid
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

When I tried the the hello world exemple I thought that Locust would try adding the missing scheme for the host.
What I found was that locust tries to launch the user as fast as posible and just spams the printout.

As you can see it loops as fast as possible. I tried to look after a similar issue but I did not found anything.
Wouldn't that be good to have a better error exit then spam looping when something core like the host is wrong.

~~~sh
[2024-02-01 09:30:54,511] d189d6727fd5/ERROR/locust.user.task: Invalid URL 'localhost/hello': No scheme supplied. Perhaps you meant https://localhost/hello?
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.11/site-packages/locust/user/task.py", line 342, in run
    self.execute_next_task()
  File "/home/vscode/.local/lib/python3.11/site-packages/locust/user/task.py", line 375, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/vscode/.local/lib/python3.11/site-packages/locust/user/task.py", line 492, in execute_task
    task(self.user)
  File "/workspaces/popins-v3/locustfiles/demo.py", line 8, in hello_world
    self.client.get("/hello")
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/locust/clients.py", line 136, in request
    response = self._send_request_safe_mode(method, url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/locust/clients.py", line 181, in _send_request_safe_mode
    return super().request(method, url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'localhost/hello': No scheme supplied. Perhaps you meant https://localhost/hello?

[2024-02-01 09:30:54,512] d189d6727fd5/ERROR/locust.user.task: Invalid URL 'localhost/hello': No scheme supplied. Perhaps you meant https://localhost/hello?
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.11/site-packages/locust/user/task.py", line 342, in run
    self.execute_next_task()
  File "/home/vscode/.local/lib/python3.11/site-packages/locust/user/task.py", line 375, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/vscode/.local/lib/python3.11/site-packages/locust/user/task.py", line 492, in execute_task
    task(self.user)
  File "/workspaces/popins-v3/locustfiles/demo.py", line 8, in hello_world
    self.client.get("/hello")
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/locust/clients.py", line 136, in request
    response = self._send_request_safe_mode(method, url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/locust/clients.py", line 181, in _send_request_safe_mode
    return super().request(method, url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'localhost/hello': No scheme supplied. Perhaps you meant https://localhost/hello?

[2024-02-01 09:30:54,513] d189d6727fd5/ERROR/locust.user.task: Invalid URL 'localhost/hello': No scheme supplied. Perhaps you meant https://localhost/hello?
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.11/site-packages/locust/user/task.py", line 342, in run
    self.execute_next_task()
  File "/home/vscode/.local/lib/python3.11/site-packages/locust/user/task.py", line 375, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/vscode/.local/lib/python3.11/site-packages/locust/user/task.py", line 492, in execute_task
    task(self.user)
  File "/workspaces/popins-v3/locustfiles/demo.py", line 8, in hello_world
    self.client.get("/hello")
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/locust/clients.py", line 136, in request
    response = self._send_request_safe_mode(method, url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/locust/clients.py", line 181, in _send_request_safe_mode
    return super().request(method, url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'localhost/hello': No scheme supplied. Perhaps you meant https://localhost/hello?

[2024-02-01 09:30:54,514] d189d6727fd5/ERROR/locust.user.task: Invalid URL 'localhost/hello': No scheme supplied. Perhaps you meant https://localhost/hello?
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.11/site-packages/locust/user/task.py", line 342, in run
    self.execute_next_task()
  File "/home/vscode/.local/lib/python3.11/site-packages/locust/user/task.py", line 375, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/vscode/.local/lib/python3.11/site-packages/locust/user/task.py", line 492, in execute_task
    task(self.user)
  File "/workspaces/popins-v3/locustfiles/demo.py", line 8, in hello_world
    self.client.get("/hello")
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/locust/clients.py", line 136, in request
    response = self._send_request_safe_mode(method, url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/locust/clients.py", line 181, in _send_request_safe_mode
    return super().request(method, url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'localhost/hello': No scheme supplied. Perhaps you meant https://localhost/hello?

[2024-02-01 09:30:54,515] d189d6727fd5/ERROR/locust.user.task: Invalid URL 'localhost/hello': No scheme supplied. Perhaps you meant https://localhost/hello?
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.11/site-packages/locust/user/task.py", line 342, in run
    self.execute_next_task()
  File "/home/vscode/.local/lib/python3.11/site-packages/locust/user/task.py", line 375, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/vscode/.local/lib/python3.11/site-packages/locust/user/task.py", line 492, in execute_task
    task(self.user)
  File "/workspaces/popins-v3/locustfiles/demo.py", line 8, in hello_world
    self.client.get("/hello")
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/locust/clients.py", line 136, in request
    response = self._send_request_safe_mode(method, url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/locust/clients.py", line 181, in _send_request_safe_mode
    return super().request(method, url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'localhost/hello': No scheme supplied. Perhaps you meant https://localhost/hello?
~~~

### Command line

locust -f demo.py --headless --users 1 --spawn-rate -1 -H localhost

### Locustfile contents

```python3
from locust import HttpUser, task

class HelloWorldUser(HttpUser):
    @task
    def hello_world(self):
        self.client.get("/hello")
        self.client.get("/world")
```

### Python version

3.11.4

### Locust version

2.21.0

### Operating system

Debian 11

### PR DESCRIPTION
**Pull request by ilyabe**
Fixes #2575 

Based on the discussion in #2610, validates the `--headless` and `--host` options. 

- If `--headless` is passed, then `--host` is required
- If `--host` value doesn't include protocol, an error message is printed
- Updated all tests that had `--headless` without `--host`
- Added tests for the new error messages

These changes are only for the CLI. I'll make a separate PR for the webui. 

If there's a better approach or anything to improve, I'm happy to.

### CODE REVIEW

**Comment by cyberw** [comment]
> If --headless is passed, then --host is required

`--host` should not be required, because it can also be set on the User class.

**Comment by ilyabe** [comment]
> what if it is not an http test at all?

Then this is trickier. We could have a list of supported protocols (e.g. `http`, `https`, `ftp`, `ssh`, `irc`, etc.) but that might be too limiting? We could check that `://` is in the `host` but I'm not sure all protocols specify a `://` syntax. Maybe things are fine as is?

**Comment by ilyabe** [comment]
I updated the PR with one more approach. It uses `urllib`'s `urlparse` to check that the parsed `host` has a `scheme` value. Just another option. If there are any issues with this, let me know :)

**Comment by cyberw** [comment]
> > what if it is not an http test at all?
> 
> Then this is trickier. We could have a list of supported protocols (e.g. `http`, `https`, `ftp`, `ssh`, `irc`, etc.) but that might be too limiting? We could check that `://` is in the `host` but I'm not sure all protocols specify a `://` syntax. Maybe things are fine as is?

I wouldnt necessarily call it "fine", but the current design makes it really hard to fix :-/

I wonder... Perhaps HttpUser could validate its `host` attribute on initialization and stop the test if it is not a valid prefix? (probably we should allow None, but that is not the key issue) Or maybe throwing an exception is enough to stop the user from being spawned. I dont really have time to explore how feasible that would be, but that way different Users can use different schemes.

**Pull request closed without merging**
