### PR TITLE
Add response_length to request_failure event

### PR DESCRIPTION
**Pull request by cyberw**
Like with request_success... This breaks compatibility with existing tests that use event handlers with positional arguments. Maybe it is worth a bumped minor version, to indicate that to users.

### CODE REVIEW

**Comment by heyman** [comment]
Nice! The `response_length` should also be passed along to the `log_error()` call in `on_request_failure` on this line:

https://github.com/locustio/locust/blob/795b5a14dd5b0991fec5a7f96f0d6491ce19e3d0/locust/stats.py#L616

> Maybe it is worth a bumped minor version, to indicate that to users.

Yeah, I think that the next version we release should be 0.13 (the new wait time API have now also been merged).

**Comment by heyman** [comment]
Hmm, we might also need something like #1088, but for response_length

**Comment by cyberw** [comment]
> Hmm, we might also need something like #1088, but for response_length

Responses that have an undefined response_length? Maybe... but I think we're ok with counting them as zero for now. Or do you feel this relates to the PR? As we dont calculate average response length, it doesnt really hurt that undefined response length cannot be separated from zero response times.

**Comment by heyman** [comment]
> As we dont calculate average response length

We do calculate the average response length:

image

We've been using 0 for failures up until now (since it wasn't available in the event params), so it wouldn't make it *more* wrong to keep doing it, though maybe it would be worth fixing it now when it *is* available?

**Comment by cyberw** [comment]
Oh, I didnt see it in the StatsEntry object, so I thought it wasnt used. Maybe I should start using the web UI more :)

But it looks like it is already fixed by my changes?

image

**Comment by heyman** [comment]
> But it looks like it is already fixed by my changes?

Ah, nice!

Then I guess we can merge this, and perhaps create a separate issue for excluding failures with None as response_length, from the average response size.

**Pull request merged**
