### PR TITLE
Don't log state change if it's the same

### PR DESCRIPTION
**Pull request by max-rocket-internet**
Resolves https://github.com/locustio/locust/issues/1577

### CODE REVIEW

**Comment by cyberw** [comment]
Are you sure there is not an underlying issue? I dont see why we should make tons of state changes to the same state...

**Comment by max-rocket-internet** [comment]
True. I can find out why something is continually updating the state to the same value.

**Comment by max-rocket-internet** [comment]
It's from here: https://github.com/locustio/locust/blob/master/locust/runners.py#L624

I will test a different fix then 🙂

**Comment by cyberw** [comment]
Nice! maybe just add `and not self.state == STATE_STOPPING` to that if statement...

**Comment by max-rocket-internet** [comment]
OK done that now some test is failing. I will look into it.

**Pull request merged**
