### PR TITLE
Remove step load feature

### PR DESCRIPTION
**Pull request by max-rocket-internet**
Resolves https://github.com/locustio/locust/issues/1575

### CODE REVIEW

**Comment by cyberw** [comment]
Nice! But can you give an error when someone tries to use step load? Like the --slave parameter is handled atm.

**Comment by cyberw** [comment]
@max-rocket-internet Any chance you'll have time to finish this soon? :)

**Comment by max-rocket-internet** [comment]
@cyberw pushed changes, I think that's it 🙂

**Comment by cyberw** [comment]
thanks!

**Pull request merged**
