### PR TITLE
Update TaskSet to use deque

### PR DESCRIPTION
**Pull request by Hchanni**
Saw a comment in Issue #2653 and thought I'd give it a try, just updates the insertion to the first element to use `appendleft` and also updates the type of `_task_queue` to use the collections deque.

### CODE REVIEW

**Comment by Hchanni** [comment]
Interesting, so I tried the test `python -m tox -e fail_fast_test_main` locally, and seems to fail even if I were to remove my changes. Any ideas?

**Comment by cyberw** [comment]
Did you figure it out?

**Comment by Hchanni** [comment]
> Did you figure it out?

Not yet, spinning up a new branch and messing with the tests, it’s weird cause the tests are failing even on a non altered master branch, for some reason the workers just don’t connect and it times our.

**Comment by cyberw** [comment]
👍 let me know if you need help.

**Comment by cyberw** [comment]
@Hchanni I tweaked your solution a little and made a new PR. Thanks for the inspiration :)

**Comment by Hchanni** [comment]
Oh shoot thanks for getting the fix out @cyberw got wrapped up with some locust stuff at work haha and didn't get a chance to actually dig into it. I'll take a look at the PR I'm actually curious to see why mine was failing

**Pull request closed without merging**
