### PR TITLE
Only warn about open file limit when not running as master

### LINKED ISSUE #1572: Misleading log message in distributed mode
### Describe the bug
When running locust in distributed mode you can still get this warning message on the master node:
```
/WARNING/locust.main: System open file limit setting is not high enough for load testing, and the OS didn't allow locust to increase it by itself. See https://github.com/locustio/locust/wiki/Installation#increasing-maximum-number-of-open-files-limit for more info.
```
Since the master won't execute any of the tests this warning is misleading.

### Expected behavior

No log message about open file limit on master when running distributed

### Actual behavior
Log message about low open file limit on instance running master mode

### Steps to reproduce
 
Run `locust --master` on a host with low open file limit (e.g 2048).

### Environment

- OS: locust docker image running on Linux host
- Python version: Embedded version in docker image with tag `1.2.3`
- Locust version: 1.2.3
- Locust command line that you ran: `locust --master`
- Locust file contents (anonymized if necessary): N/A

### PR DESCRIPTION
**Pull request by parberge**
Fix #1572

### CODE REVIEW

**Comment by cyberw** [comment]
Lgtm, except for the accidental reformatting..

**Comment by parberge** [comment]
> Lgtm, except for the accidental reformatting..

So weird, because I use `black` and it changed it for me :(

I will restore that then.

**Comment by cyberw** [comment]
That *is* weird. Maybe you have a different black version?

**Comment by parberge** [comment]
> That _is_ weird. Maybe you have a different black version?

Hm something with my vs code it seems. If I do it manually it doesn't change the file:
```
locust on ⎇ master [⇡?] via 🐍 v3.8.2 (locust-G6mk0hEc) ❯ black --version
black, version 20.8b1
locust on ⎇ master [⇡?] via 🐍 v3.8.2 (locust-G6mk0hEc) ❯ git diff locust/main.py
locust on ⎇ master [⇡?] via 🐍 v3.8.2 (locust-G6mk0hEc) ❯ black locust/main.py
All done! ✨ 🍰 ✨
1 file left unchanged.
```
🤷

**Comment by cyberw** [comment]
perhaps you opened vscode in a different folder and that made it not pick up the pyproject.toml?

**Pull request merged**
