### PR TITLE
Added --html option to generate HTML report

### PR DESCRIPTION
**Pull request by vsapronov**
This is very useful when running locust in headless mode.

### CODE REVIEW

**Comment by cyberw** [comment]
Cool stuff! Can you add a test case?

**Comment by vsapronov** [comment]
> Cool stuff! Can you add a test case?

Hi, I think the functionality that I have extracted is under tests that are hitting `/stats/report` here: https://github.com/locustio/locust/blob/master/locust/test/test_web.py#L300-L345.

**Comment by cyberw** [comment]
Can you add a "real" test in test_main.py ? I agree that some of the underlying features are tested, but not the writing to file etc.

**Comment by cyberw** [comment]
@vsapronov ?

**Comment by cyberw** [comment]
replaced by #1637

**Pull request closed without merging**
