### PR TITLE
Allow skipping the logging setup

### PR DESCRIPTION
**Pull request by Exide**
New CLI option:

    --skip-log-setup

This would allow people to setup their own logging configuration. It would also provide a workaround for #163.

### CODE REVIEW

**Comment by Exide** [comment]
I've not used Codecov before so I'm finding it difficult to understand what threshold I need to meet. Let me know what is needed and I'll rectify it.

**Comment by soulrebel** [comment]
I was trying to use pudb to do some simple debugging, but it fails to open the console interface due to the wrapping of standard error/output

**Comment by Exide** [comment]
@soulrebel This PR would allow you to skip the call to ```log.setup_logging``` which is where that wrapper is established.

**Comment by SpencerPinegar** [comment]
This should be merged with the code base -- vital when testing code or else the unittestpy.py with error out with -- 'StdOutWrapper' object has no attribute 'getvalue' -- if this functionality could be incorporated into the wrapper that would be cool, but it looked like the getvalue function had other dependencies within the unittestpy.py module.

**Comment by aldenpeterson-wf** [comment]
This LGTM. 

Anyone have objections to me merging this?

**Comment by tally38** [comment]
Also ran into this issue, and would like this to be merged!

**Pull request merged**
