### PR TITLE
Docs: Import wiki to docs

### PR DESCRIPTION
**Pull request by plaindocs**
- added imports to TOC
- deleted Home.rst
- removed spurious html formatting `li`, `h4` etc
- fixed H1s
- rename/move files 
- actually look at content :-p
- migrated links to current content
- moved articles to discussion forum
- promoted "Increase my request rate/RPS"
- integrated installation troubleshooting

## Not done

- automation of examples
- Move "clear cookies" FAQ

### CODE REVIEW

**Comment by cyberw** [comment]
A good start, but needs some work. 

`Increase my request rate/RPS` is great and really deserves a top level entry (with a link to the discussion forum for followup-questions). 

Same with installation issues (but it needs to be merged nicely with the current installation page somehow)

Articles need to be checked that they still exist (remove the oldest ones) and added as an entry in the discussion forum. It can still be a page in the docs, but maybe just a few titles and a link to that entry.

"Clear cookies, to make the next task iteration seem like a new user to my system under test" can be moved somewhere, maybe here: https://docs.locust.io/en/stable/writing-a-locustfile.html#examples (and we should list the examples there with a short description instead of just pointing to the examples/ directory - ideally by generating the list dynamically)

**Comment by plaindocs** [comment]
@cyberw this is probably at the good enough stage, what do you think?

**Comment by cyberw** [comment]
A few things:

Installation issues needs a proper introduction, probably even its own page, linked here 

> Install the package (check [the wiki](https://github.com/locustio/locust/wiki/Installation) if the installation fails)

And some of the titles (the ones that are error messages) should be formatted as code. It looks a bit weird atm:

image

There is some broken formatting here. And the last part about "Launch locust -f scripts/locustfile.py..." doesnt fit there, where did that come from?

image

**Comment by cyberw** [comment]
There's an extra "the" here:

> If you need some help digging into server side problems, or you’re having trouble generating enough load to saturate your system, take a look at the [Increasing the request rate](https://locust--2734.org.readthedocs.build/en/2734/increasing-request-rate.html#increaserr).

Probably turning the sentence around to start with "having trouble generating enough load" fits better with the title of the page, but perhaps the title could be reworked as well?

**Comment by cyberw** [comment]
Formatting: 

image

**Comment by cyberw** [comment]
This screenshot is too small (maybe it has always been this way)

image

**Comment by cyberw** [comment]
Random line breaks in the titles imported from the wiki:

image

**Comment by cyberw** [comment]
Other than that, great stuff!

**Comment by plaindocs** [comment]
I should have said, I'm trying to do the minimum viable import so we can merge this, so I'm concentrating more on importing the wiki as is rather than making sure all of the imported docs are in tip top shape, then we can iterate over it as part of the overhaul.

The code/title heading is in that psutil thing is gonna look weird either way unless we reword it. 
The `locust -f scripts/locustfile.py` is also as in the wiki. I've refactored that section (but what should the last code line read)

- Fixed the random line breaks
- Fixed 'the the'
- Fixed code formatting
- Fixed image width

**Comment by cyberw** [comment]
> I should have said, I'm trying to do the minimum viable import so we can merge this, so I'm concentrating more on importing the wiki as is rather than making sure all of the imported docs are in tip top shape, then we can iterate over it as part of the overhaul.

Gotcha!

> The code/title heading is in that psutil thing is gonna look weird either way unless we reword it.
The locust -f scripts/locustfile.py is also as in the wiki. I've refactored that section (but what should the last code line read)

The "deploy on local environment" part of Installation in the wiki is confusing and broken. Just nuke it.

Still a few broken line endings from the import (but you can fix it later if you want)

image

**Comment by cyberw** [comment]
oh, and formatting the "FAQ" page (if it should even exist at all, I'd prefer moving the entries there to other places, but there is no rush with that. What should be fixed is the explicit reference to the wiki :) (you can just remove it)

> If you have questions about Locust that are not answered here, please check [StackOverflow](https://stackoverflow.com/questions/tagged/locust), or post your question there. This wiki is not for asking questions but for answering them :)

**Comment by plaindocs** [comment]
Agreed - migrating FAQ to other places usually makes more sense. But to do that properly I've have to take a proper look at the contents. :-D

**Comment by cyberw** [comment]
Looks good now! I'll squash the commits, unless you want a plain merge?

**Comment by plaindocs** [comment]
Whatever your normal is! Squashed is fine with me.

**Comment by cyberw** [comment]
Btw, there's an open PR for changing the build/install process (#2725) so don't for some reason go off spending time documenting the current install procedure :)

**Pull request merged**
