### PR TITLE
Add equal weights flag

### PR DESCRIPTION
**Pull request by shekar-stripe**
Issue: https://github.com/locustio/locust/issues/1838

### CODE REVIEW

**Comment by cyberw** [comment]
👍👍 as for wording, I kind of prefer ”uniform” to ”same” but. 

And as you are (correctly) changing weights for Users and not just tasks, I think the parameter name is kind of confusing. 

Does this also work for TaskSets?

**Comment by shekar-stripe** [comment]
I also prefer uniform, the reason I had to change it to same was because argparse thought a flag with --uniform-* was too close to --user (and could get confusing with the --u shorthand).

I can see why you think the parameter name is confusing, I can definitely change it. Something like `same-weights`? (Is there some way around the argparse error? Should I want to get around it?) 

Yes, I believe I tested TaskSets as well. Please let me know if there's something else I should test further. I'm new to locust (and Stripe, just joined less than a month ago) so it's definitely a possibility I missed something.

**Comment by cyberw** [comment]
> I also prefer uniform, the reason I had to change it to same was because argparse thought a flag with --uniform-* was too close to --user (and could get confusing with the --u shorthand).
> 
> I can see why you think the parameter name is confusing, I can definitely change it. Something like `same-weights`? (Is there some way around the argparse error? Should I want to get around it?)

Not sure whether there is a way, but go ahead and try. The risk of confusion should be small. —uniform-weights would be ideal. 

> Yes, I believe I tested TaskSets as well. Please let me know if there's something else I should test further. I'm new to locust (and Stripe, just joined less than a month ago) so it's definitely a possibility I missed something.

I think the one thing you maybe havent tested is tasks specified as `tasks = {my_task: 3, another_task: 1}`?

https://docs.locust.io/en/stable/writing-a-locustfile.html#id2

or does it work for those too?

**Comment by shekar-stripe** [comment]
Unfortunately, I don't think it's possible without enabling a flag that disables abbreviations which would introduce breaking changes: https://realpython.com/command-line-interfaces-python-argparse/
I've kept the internal calls `uniform` and just the flag `same`. 

I didn't test user tasks added as a dict, that's updated now. LMK if this is good to merge.

**Comment by cyberw** [comment]
Cool! I think you can ignore that failing test in the latest run. I’m confused by the argument parsing issue though. How come —stop-timeout doesnt collide with --show-task-ratio for example?

**Comment by cyberw** [comment]
Maybe —equal-weights works?

**Comment by shekar-stripe** [comment]
I'm honestly not sure why the argument parsing issue is happening. I tried switching the flags to mirror the `--stop-timeout` and `--show-task-ratio` example, but to no avail. I also tried moving the new argument into the same arg group as users, but that also threw an error. If you have any other ideas, please let me know! 

I changed the flag to --equal-weights.

**Comment by cyberw** [comment]
Does the name —equal-weights work then? If so, update the method name etc as well.

**Comment by shekar-stripe** [comment]
Done!

**Comment by cyberw** [comment]
Cool!

**Comment by shekar-stripe** [comment]
Hey @cyberw, when do you think this change will be released as part of an official version? Per my company's security policy, we are only allowed to use official releases rather than the "bleeding edge" as mentioned in the docs...

**Comment by cyberw** [comment]
You can use prereleases, right? I’m working on adding a git workflow that builds and pushes a prerelease version (something like 2.1.0devX) on every PR merge.

**Comment by cyberw** [comment]
Ok, that took me longer than I had hoped :)

Anyways, you should now be able to do
`pip install -U --pre locust`
or (to get the latest one just now)
`pip install locust==2.1.1.dev53`

**Comment by shekar-stripe** [comment]
Awesome, thank you! Really appreciate it.

**Pull request merged**
