### PR TITLE
Feature stats exceptions csv

### PR DESCRIPTION
**Pull request by aek**
Solve #1673

### CODE REVIEW

**Comment by cyberw** [comment]
Lgtm. I dont use the built in csv writing though, so it would be great if someone else can weigh in as well.

**Comment by lhupfeldt** [comment]
Looks good.
I think that as a followup change it should be consideret to start using lists and loops to reduce the number of places needing change if new files are added.

**Comment by aek** [comment]
@lhupfeldt I don’t understand what you mean 
Could you elaborate please?

**Comment by lhupfeldt** [comment]
I mean your PR looks fine, but after it is merged, maybe there should another PR to use be a list of filesnames such that e.g.:

`    def setUp(self):
        super().setUp()
        self.remove_file_if_exists(self.STATS_FILENAME)
        self.remove_file_if_exists(self.STATS_HISTORY_FILENAME)
        self.remove_file_if_exists(self.STATS_FAILURES_FILENAME)
        self.remove_file_if_exists(self.STATS_EXCEPTIONS_FILENAME)
`
Could be written as:

`    def setUp(self):
        super().setUp()
        for fn in  self.stats_files:
            self.remove_file_if_exists(fn)
`

**Comment by aek** [comment]
I see it now, I agree with that. I could include it in this one if it will be considered to be merged too

**Comment by lhupfeldt** [comment]
I would personally prefer is as a separate PR. Makes it easier to see what this PR is about, but i'm not a maintainer.

**Comment by aek** [comment]
Let's wait to see this one merged then
Thanks

**Pull request merged**
