### PR TITLE
Show custom arguments in web ui and forward them to worker

### LINKED ISSUE #1822: locust should add extending blocks to index.html to change the start test and edit test options
### Is your feature request related to a problem? Please describe.

I want to be able to configure different options when starting a test with another field/toggle other than just the spawn rate and number of users. 

### Describe the solution you'd like

I would like to have `{% extended_on_start %}` and `{% extended_edit_test %}` to `index.html` so I can add in my own code new input fields to specify what kind of test I want. I am writing changes to my loadtester and based off of this toggle I want the code to set a flag that will tell what object to create. 

### Describe alternatives you've considered

I have considered forking the respository and changing the locust UI myself but I think is a little overkill for the small change I am thinking of. I have also considered adding a screen before you get to the start menu with the toggles but I am not sure how to do this currently and I think it will not look the best.

### PR DESCRIPTION
**Pull request by cyberw**
This is WIP. I'm not sure showing all custom arguments in the UI is the best solution (and it would also be nice to be able to show some of the default ones). What do you think @TWoeste

I tried to make that "advanced" tab thingy but it turned out to be too much work :)

### CODE REVIEW

**Comment by TWoeste** [comment]
I do think this is a cleaner approach to adding custom start UI. I do think that the whole point to add these arguments would be to access them somehow in your tasks to change how they act (so on the worker runner for distributed tests). For instance if you wanted to specify the username and password of the requests it would be best if you could access these in the worker to set them in the header of the requests. Another downside to this approach is all of your custom fields will be text boxes so its hard to predict what users will put there. In the end I think its a good approach to solve my issue. In my local branch I solved the problem with not being able to access the variables in the worker branch by sending a message from the master runner to the worker runner as suggested [here](https://stackoverflow.com/a/68657455/16236463). @cyberw

**Comment by TWoeste** [comment]
Would the parsed_options be populated with the correct data on the worker instance of env?

**Comment by cyberw** [comment]
> I do think that the whole point to add these arguments would be to access them somehow in your tasks to change how they act (so on the worker runner for distributed tests). For instance if you wanted to specify the username and password of the requests it would be best if you could access these in the worker to set them in the header of the requests.

This approach makes them accessible in Users by `self.environment.parsed_options.my_argument`

> Would the parsed_options be populated with the correct data on the worker instance of env?

Not automatically no, that would also have to be addressed (hence the draft status :)

**Comment by TWoeste** [comment]
This all looks amazing to me :). I think it will become one of the more uses locust feature when implements. Thanks!

**Comment by cyberw** [comment]
@TWoeste Can you try this out before I merge it?

**Review by TWoeste — APPROVED** [review]
LGTM, Tested it with the example file!

**Pull request merged**
