### PR TITLE
Update configuration.rst to show minimalistic config example

### PR DESCRIPTION
**Pull request by vkuehn**
As dicussed in the issue #2987 a minimalistic  eample of config would prevent a reoccurence

### CODE REVIEW

**Comment by cyberw** [comment]
> No Options are selected which would make Locust run e.g. headless or distributed

Adding an example is good, but headless and distributed options do exactly what they do on command line, so there's no need to mention them specifically, is there? 

I know they threw you off a little bit, but with an example, hopefully this is less likely to happen.

**Comment by vkuehn** [comment]
@cyberw The reason to add this example was that starting with Locust comming from command line lead into a trap with the existing example., It took me while and help of an issue here to find out that the existing example would simple not work as it relies to TAG, MASTER..
so the intention was to add a most simple working example matching the locust.py example in the docs

**Comment by cyberw** [comment]
I know what you're trying to achieve, but "No Options are selected which would make Locust run e.g. headless or distributed" makes no sense, because headless is completely valid in a config file and distributed settings _can_ be. Plus it is not grammatically correct so I'm not sure what you even mean...

**Comment by vkuehn** [comment]
you are right headless should be in a config file.

**Comment by cyberw** [comment]
I'm not saying it needs to be in the config file, I'm saying this sentence is misleading "No Options are selected which would make Locust run e.g. headless or distributed."

**Comment by vkuehn** [comment]
sorry misunderstood that. Actually the whole sentence could be removed and just add a small example which would be useable when comming from the commandline examples straight

**Comment by cyberw** [comment]
thx!

**Pull request merged**
