### PR TITLE
add a configuration option for specifying a worker heartbeat interval

### PR DESCRIPTION
**Pull request by bioker**

### CODE REVIEW

**Comment by bioker** [comment]
I have noticed that there is no option to configure this parameter.

I have faced a situation when the heartbeat fails but workers seem to be healthy while doing this lab project: https://github.com/bioker/mysql-lab/blob/f85ea857d0c4b29261569eadcca6b5344ac7eed1/docker-compose.yaml#L4.

Running the project with the custom docker image I build from my version shows that the increased heartbeat helps to avoid such problems and the test is still working well.

Maybe it's worth checking why it fails in the first place, but it seems harder than adding this parameter and I suppose it can be useful in some flaky environments anyway so here is the PR.
I hope you will find it useful too.

Also seems to be related to the following issues:
https://github.com/locustio/locust/issues/1787
https://github.com/locustio/locust/issues/1843

**Comment by bioker** [comment]
Ah, have followed the issue history and noticed this feature request so linking it also:
https://github.com/locustio/locust/issues/1897

**Comment by bioker** [comment]
This change represents how I have used the updated version: https://github.com/bioker/mysql-lab/commit/eedbb5a31f717acbc128ebf4ba3a05fe88d01458

**Comment by cyberw** [comment]
Hmm... those values are already customizable, and I'm not sure they are worthy of a command line setting.

```
from locust import runners
runners.HEARTBEAT_INTERVAL = 2
```

**Comment by bioker** [comment]
Ok, I see, thanks for the example

**Pull request closed without merging**
