### PR TITLE
Added explicit type check for headers in fasthttp.py

### PR DESCRIPTION
**Pull request by lundstrj**
I accidentally tried to use supply a set instead of a dictionary and it took me way longer than it should have to figure out what was wrong. These two lines of code in locust would have gone a long way to help me out.

### CODE REVIEW

**Comment by cyberw** [comment]
Well.. as there's no way to recover from this error and we dont want to add checks for all every sort of parameter. I dont really think this is worth it.

This should have been caught by a linter, but for some reason, mine (pylint+vscode language server) don't see a problem passing something else, maybe I can fix that...

**Comment by lundstrj** [comment]
Yeah I mean if you pass a non dictionary locust will crash and that's that. I just wanted it to be easier for the user to find their input error faster. I did this:
`headers = {"Content-Type:application/json"}`

Instead of this:
`headers = {"Content-Type":"application/json"}`

And I am ashamed of how long it took me to spot my error.
This assert would have helped. Perhaps it's too expensive to check the type of headers in every request?

As much as I like to develop in Python I also find myself practicing software constraints a lot more than I do in other more less forgiving languages. I try to assert all of my assumptions on the input at the beginning of my functions, if I can do so reasonably quickly/affordably.

**Comment by cyberw** [comment]
This ticket made me go back and revisit our type hinting. Turns out, mypy was unable to automatically detect the type of FastHttpUser.client, so this type of error could not have been detected. 

I fixed that now in https://github.com/locustio/locust/commit/4ba878139cfd645887809f8002e8ed734a4c80be

So now (if you use latest master, at the next release if you dont), you can use mypy to find these kinds of errors. I highly recommend running that - in most editors you can run this on-save, so you'll never have to run into this kind of problem.

Here's what it should look like in vscode for instance:
image

**Comment by lundstrj** [comment]
@cyberw Alright, cool man. My PR was rejected BUT it seems I had a positive impact on the code base anyway and at the end of the day, that is what I wanted.

**Pull request closed without merging**
