### PR TITLE
#1832 Displaying locustfile and tasks ratio information on index.html

### PR DESCRIPTION
**Pull request by tyge68**
As discribed on #1832 , here is the suggested changes to allow displaying a bit more information about the current locustfile / tasks that will be executed in the Web UI.

About the look n feel any suggestions to make it looks nicer would be welcome.

### CODE REVIEW

**Comment by tyge68** [comment]
Here is how it would looks like
Screenshot 2021-07-30 at 18 22 27

**Comment by cyberw** [comment]
Cool stuff. I'll give it a look some time next week (after we've released 2.0 & followed up on any issues that arise from it)

**Comment by cyberw** [comment]
I see the need for this, but would like to hide it behind an advanced tab or something. Needs some tests too.

**Comment by cyberw** [comment]
Github seems to have issues with the tests. Try merging master.

**Comment by cyberw** [comment]
Ignore the docker fail in the build, that is probably my bad.

**Comment by tyge68** [comment]
@cyberw  do you know if tests can be retriggered (without any commits on my side) ?

**Comment by cyberw** [comment]
> @cyberw do you know if tests can be retriggered (without any commits on my side) ?

Done.

**Comment by cyberw** [comment]
@tyge68 If you fix this soon it might be in time for 2.2 release :)

**Pull request closed without merging**
