### PR TITLE
Added introduction of Boomer

### PR DESCRIPTION
**Pull request by myzhan**
Now, we are able to write test scenarios in golang.

add @cgoldberg as a reviewer.

### CODE REVIEW

**Comment by chris-surge** [comment]
@myzhan I'd say don't change anything in that index file other than the link, that commit will retrigger the CI and it should pass.

**Comment by cgoldberg** [comment]
@chris-surge 

> I'd say don't change anything in that index file other than the link,

good idea... there shouldn't be unrelated whitespace changes in a PR.

> retrigger the CI and it should pass.

That's not causing CI to fail.  travis-ci fails on python2.6 because it's trying to install gevent 1.2 which doesn't work with 2.6.  We should just drop 2.6 support to fix that (see: #515)

for other versions of Python, travis-ci is failing with:

```
======================================================================
FAIL: test_request_stats_no_content_length (locust.test.test_stats.TestRequestStatsWithWebserver)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/locustio/locust/locust/test/test_stats.py", line 165, in test_request_stats_no_content_length
    self.assertEqual(global_stats.get(path, "GET").avg_content_length, len("This response does not have content-length in the header"))
AssertionError: 0 != 56
```

It looks like we have some bad tests in test_stats.py... hopefully someone has time to fix.

**Comment by myzhan** [comment]
@chris-surge sorry for the whitespaces, atom added them. I will check this later.

@cgoldberg I fixed some tests, in another PR.

**Comment by myzhan** [comment]
@chris-surge By default, atom removes trailing whitespace.

**Comment by mbeacom** [comment]
@myzhan Can you repush this? The tests **should** pass now.

**Comment by myzhan** [comment]
@mbeacom I reopened this PR, the tests had passed.

**Comment by aldenpeterson-wf** [comment]
This lgtm, @cgoldberg you want to merge this?

**Comment by cgoldberg** [comment]
the whitespace changes were not removed as asked, but merging anyway :)

**Pull request merged**
