### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by balaji2711**
I have updated the locust usage that was not mentioned in the documentation. Kindly review and merge this pull request.

### CODE REVIEW

**Comment by cyberw** [comment]
Not sure these things need this much focus in the docs (although we should definitely mention that other protocols can be supported, if it isnt already mentioned). Websockets is not even part of locust-core, so mentioning it without referencing locust-plugins is just confusing.

**Comment by balaji2711** [comment]
Ok, As you said, At least we can mention the supported protocols and also we can mention about the custom tasks in the document, It's not mentioned anywhere in the docs. If required, we can provide the sample snippet as well.

**Comment by balaji2711** [comment]
Hi @cyberw, 
Could you please reject this pull request if that's not useful?

**Comment by cyberw** [comment]
> Hi @cyberw,
> Could you please reject this pull request if that's not useful?

Ok! I’m sure the documentation can be improved in other places, so if you find other things feel free to open a new PR.

**Pull request closed without merging**
