### PR TITLE
csv from command line

### PR DESCRIPTION
**Pull request by kevinpetersavage**
Hi guys, 

We were trying to use locust with our Jenkins CI. In order to get feedback to Jenkins we wanted to get the CSV files that are produced in the web ui from the command line interface. I found this was nearly just moving stuff about in the code so I just did it.

It would be great if this could be included in a future release.

Great tool btw!

Kevin

### CODE REVIEW

**Comment by kowalcj0** [comment]
I'd love to have the option to store csv reports. How can we contribute to this PR to get it on master?

**Comment by hampsterx** [comment]
+1

**Comment by louisnayegon** [comment]
+1

**Comment by thedrow** [comment]
I think that this should be closed until someone tackles it.

**Comment by cgoldberg** [comment]
@thedrow i think #252 supersedes this

**Comment by giantryansaul** [comment]
+1 really would love this feature in master.

**Comment by fatso83** [comment]
This could be closed with #252 pending.

**Comment by sngpranay** [comment]
To download csv from command line, `curl localhost:8089/stats/requests/csv -o requests_stats.csv `

**Comment by sj2208** [comment]
@heyman  anything on such feature of getting csv while running in no-web mode ?

**Comment by mbeacom** [comment]
Closed in favor of #612 (merged) - Thank you!

**Pull request closed without merging**
