### PR TITLE
Escape user supplied data in html report (#2126)

### PR DESCRIPTION
**Pull request by herrmanntom**
This is a quick fix for issue #2126, possibly not the most elegant solution.

### CODE REVIEW

**Comment by cyberw** [comment]
LGTM. Have you tested a few cases? Like spaces in filenames etc?

**Comment by cyberw** [comment]
I think the problems on GH are real errors. Can you check if your package versions are different from the ones listed in the build? (or just try installing the latest ones yourself)

**Comment by herrmanntom** [comment]
Maybe I did it somehow wrong before. Now everything seems to be fixed.

**Comment by cyberw** [comment]
Thx!

**Pull request merged**
