### PR TITLE
Shutdown workers when using LoadTestShape and headless mode

### PR DESCRIPTION
**Pull request by max-rocket-internet**
Resolves https://github.com/locustio/locust/issues/1653

### CODE REVIEW

**Comment by max-rocket-internet** [comment]
@cyberw why aren't the tests running?

**Comment by cyberw** [comment]
Because travis freaked out about their free/open source tier. Heyman has reached out to them.

**Comment by cyberw** [comment]
Hmm.. I fixed test_runners.py, but there seems to still be an issue with test_main.py

 I tried adding "-L", "DEBUG", in that test, because I think quitting is only printed then, but that does not seem to be enough...

**Comment by max-rocket-internet** [comment]
Yeah I didn't run any tests as they were not working locally and the travis tests weren't working either. I didn't expect you to merge the PR until at least the travis tests were run 🙂

Shall I open another PR to fix the tests?

**Comment by cyberw** [comment]
Ah, I got a little bit ahead of myself :)

Yes, if you can open a new PR with a fix that would be great.

**Comment by aek** [comment]
I have been working with this thing of tests failing a little bit and this are my results
```log
  py36: commands succeeded
ERROR:   py37: commands failed
  py38: commands succeeded
  py39: commands succeeded
```
Only py37 tests are failling but it's due to that it's not installing the python dependencies with errors like this:
```logs

FAILED (errors=14)
ERROR: InvocationError for command /Users/axel/git-workspace/locust/.tox/py37/bin/coverage run -m unittest discover (exited with code 1)

======================================================================
ERROR: locust.test.test_runners (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: locust.test.test_runners
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/axel/git-workspace/locust/locust/test/test_runners.py", line 11, in <module>
    from locust.main import create_environment
  File "/Users/axel/git-workspace/locust/locust/main.py", line 15, in <module>
    from .argument_parser import parse_locustfile_option, parse_options
  File "/Users/axel/git-workspace/locust/locust/argument_parser.py", line 6, in <module>
    import configargparse
ModuleNotFoundError: No module named 'configargparse'


======================================================================
ERROR: locust.test.test_sequential_taskset (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: locust.test.test_sequential_taskset
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/axel/git-workspace/locust/locust/test/test_sequential_taskset.py", line 4, in <module>
    from .testcases import LocustTestCase
  File "/Users/axel/git-workspace/locust/locust/test/testcases.py", line 17, in <module>
    from locust.env import Environment
  File "/Users/axel/git-workspace/locust/locust/env.py", line 5, in <module>
    from .web import WebUI
  File "/Users/axel/git-workspace/locust/locust/web.py", line 15, in <module>
    from flask_basicauth import BasicAuth
ModuleNotFoundError: No module named 'flask_basicauth'
```

py36, py38 and py39 logs are good, like:

```logs
py36 inst-nodeps: /Users/axel/git-workspace/locust/.tox/.tmp/package/1/locust-1.4.1.zip
py36 installed: appdirs==1.4.4,black==20.8b1,certifi==2020.12.5,cffi==1.14.4,chardet==4.0.0,click==7.1.2,codecov==2.1.11,ConfigArgParse==1.2.3,coverage==5.3.1,cryptography==3.3.1,cssselect==1.1.0,dataclasses==0.8,flake8==3.8.4,Flask==1.1.2,Flask-BasicAuth==0.2.0,gevent==21.1.1,geventhttpclient==1.4.4,greenlet==1.0.0,idna==2.10,importlib-metadata==3.4.0,itsdangerous==1.1.0,Jinja2==2.11.2,locust @ file:///Users/axel/git-workspace/locust/.tox/.tmp/package/1/locust-1.4.1.zip,lxml==4.6.2,MarkupSafe==1.1.1,mccabe==0.6.1,mock==4.0.3,msgpack==1.0.2,mypy-extensions==0.4.3,pathspec==0.8.1,psutil==5.8.0,pycodestyle==2.6.0,pycparser==2.20,pyflakes==2.2.0,pyquery==1.4.3,pyzmq==21.0.1,regex==2020.11.13,requests==2.25.1,six==1.15.0,toml==0.10.2,typed-ast==1.4.2,typing-extensions==3.7.4.3,urllib3==1.26.2,Werkzeug==1.0.1,zipp==3.4.0,zope.event==4.5.0,zope.interface==5.2.0
py36 run-test-pre: PYTHONHASHSEED='3083370141'
py36 run-test: commands[0] | flake8 . --count --show-source --statistics
0
py36 run-test: commands[1] | coverage run -m unittest discover
...................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 323 tests in 95.483s

OK
py36 run-test: commands[2] | black --check .
All done! ✨ 🍰 ✨
77 files would be left unchanged.

py38 create: /Users/axel/git-workspace/locust/.tox/py38
py38 installdeps: codecov, flake8, mock, pyquery, cryptography, black
py38 inst: /Users/axel/git-workspace/locust/.tox/.tmp/package/1/locust-1.4.1.zip
py38 installed: appdirs==1.4.4,black==20.8b1,certifi==2020.12.5,cffi==1.14.4,chardet==4.0.0,click==7.1.2,codecov==2.1.11,ConfigArgParse==1.2.3,coverage==5.3.1,cryptography==3.3.1,cssselect==1.1.0,flake8==3.8.4,Flask==1.1.2,Flask-BasicAuth==0.2.0,gevent==21.1.1,geventhttpclient==1.4.4,greenlet==1.0.0,idna==2.10,itsdangerous==1.1.0,Jinja2==2.11.2,locust @ file:///Users/axel/git-workspace/locust/.tox/.tmp/package/1/locust-1.4.1.zip,lxml==4.6.2,MarkupSafe==1.1.1,mccabe==0.6.1,mock==4.0.3,msgpack==1.0.2,mypy-extensions==0.4.3,pathspec==0.8.1,psutil==5.8.0,pycodestyle==2.6.0,pycparser==2.20,pyflakes==2.2.0,pyquery==1.4.3,pyzmq==21.0.1,regex==2020.11.13,requests==2.25.1,six==1.15.0,toml==0.10.2,typed-ast==1.4.2,typing-extensions==3.7.4.3,urllib3==1.26.2,Werkzeug==1.0.1,zope.event==4.5.0,zope.interface==5.2.0
py38 run-test-pre: PYTHONHASHSEED='3083370141'
py38 run-test: commands[0] | flake8 . --count --show-source --statistics
0
py38 run-test: commands[1] | coverage run -m unittest discover
...................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 323 tests in 95.786s

OK
py38 run-test: commands[2] | black --check .
All done! ✨ 🍰 ✨
77 files would be left unchanged.
py39 recreate: /Users/axel/git-workspace/locust/.tox/py39
py39 installdeps: codecov, flake8, mock, pyquery, cryptography, black
py39 inst: /Users/axel/git-workspace/locust/.tox/.tmp/package/1/locust-1.4.1.zip
py39 installed: appdirs==1.4.4,black==20.8b1,certifi==2020.12.5,cffi==1.14.4,chardet==4.0.0,click==7.1.2,codecov==2.1.11,ConfigArgParse==1.2.3,coverage==5.3.1,cryptography==3.3.1,cssselect==1.1.0,flake8==3.8.4,Flask==1.1.2,Flask-BasicAuth==0.2.0,gevent==21.1.1,geventhttpclient==1.4.4,greenlet==1.0.0,idna==2.10,itsdangerous==1.1.0,Jinja2==2.11.2,locust @ file:///Users/axel/git-workspace/locust/.tox/.tmp/package/1/locust-1.4.1.zip,lxml==4.6.2,MarkupSafe==1.1.1,mccabe==0.6.1,mock==4.0.3,msgpack==1.0.2,mypy-extensions==0.4.3,pathspec==0.8.1,psutil==5.8.0,pycodestyle==2.6.0,pycparser==2.20,pyflakes==2.2.0,pyquery==1.4.3,pyzmq==21.0.1,regex==2020.11.13,requests==2.25.1,six==1.15.0,toml==0.10.2,typed-ast==1.4.2,typing-extensions==3.7.4.3,urllib3==1.26.2,Werkzeug==1.0.1,zope.event==4.5.0,zope.interface==5.2.0
py39 run-test-pre: PYTHONHASHSEED='3083370141'
py39 run-test: commands[0] | flake8 . --count --show-source --statistics
0
py39 run-test: commands[1] | coverage run -m unittest discover
...................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 323 tests in 95.664s

OK
py39 run-test: commands[2] | black --check .
All done! ✨ 🍰 ✨
77 files would be left unchanged.
```

**Comment by cyberw** [comment]
ping @heyman this is the PR we're waiting for a fix for :)

**Comment by heyman** [comment]
AFAICT we only log the `Quitting...` message when we run in master mode, and since the test runs locust with a LocalRunner it'll fail. Maybe we can just remove that check (https://github.com/locustio/locust/pull/1683/files#diff-81a8e34f7c9a9b06d20ff25a8b8d6f6fe983707f8ba66780659df4fe4fffa2aaR282)?

**Comment by heyman** [comment]
I removed the check in cb56d64f158bd8df2d833b9f252836d19dd39fbe (to get the Github Actions CI to work).

**Comment by max-rocket-internet** [comment]
Sorry, I've been super busy. So this is resolved now I see by just reverting my change to the test. OK cool 👍

**Pull request merged**
