### PR TITLE
Added a slaves-tab to show the id, status and number of users running on each slave.

### PR DESCRIPTION
**Pull request by TZer0**
The tab is only visible when running in master mode. The slave-counter uses the same data (slave_count is no longer passed).
screenshot from 2015-07-13 12 15 56
(The white blocks are just hiding my hostnames)

Due to the fact that the tests refuse to run on my machine, I am forced to have the centralized build system run them.

### CODE REVIEW

**Comment by TZer0** [comment]
And the tests pass.

Is this good to go?

**Comment by TZer0** [comment]
Please only merge in 23c49cc, I didn't expect the pull request to keep tracking my further changes.

**Comment by TZer0** [comment]
Didn't realise that github will actively track my master branch. I've moved some commits out of master to fix the issue.

**Comment by mbeacom** [comment]
@TZer0 Are you still interested in having this merged?

**Comment by TZer0** [comment]
@mbeacom I don't use Locust anymore, but sure - why not? It may save someone else from some serious trouble.

**Comment by mbeacom** [comment]
@TZer0 Great! Thank you for the contribution! Would you mind rebasing the branch?

**Comment by TZer0** [comment]
@mbeacom I'll fix it after work in ~9 hours.

**Comment by TZer0** [comment]
@mbeacom Should be it. I'll check up on it if the tests do not pass.

**Comment by TZer0** [comment]
Does anyone have time to merge this?

**Comment by mbeacom** [comment]
@TZer0 I'm going to test this in a few. If everything look's good, I'll merge it in!

**Pull request merged**
