### PR TITLE
Autoformat using Black. Also fix a few style complaints (trailing whitespaces)

### LINKED ISSUE #1489: Let's fix code to be PEP8 compliant?
### Is your feature request related to a problem? Please describe.

I am working on a couple PRs for locust and my IDE automatically removes trailing spaces and whitespace from blank lines. This means when I want to make a change to a file in the repo it also edits many lines to "fix" them. It's a bit annoying as I then have to go and undo all the changes. I know I could disable the feature but it has good intentions 😃

Example output from `pycodestyle`:

```
$ pycodestyle locust/exception.py
locust/exception.py:4:1: E302 expected 2 blank lines, found 1
locust/exception.py:7:1: E302 expected 2 blank lines, found 1
locust/exception.py:10:1: E302 expected 2 blank lines, found 1
locust/exception.py:13:1: E302 expected 2 blank lines, found 1
locust/exception.py:17:1: W293 blank line contains whitespace
locust/exception.py:20:80: E501 line too long (91 > 79 characters)
locust/exception.py:25:1: E302 expected 2 blank lines, found 1
locust/exception.py:28:1: E302 expected 2 blank lines, found 1
locust/exception.py:31:1: W293 blank line contains whitespace
locust/exception.py:32:80: E501 line too long (86 > 79 characters)
locust/exception.py:32:87: W291 trailing whitespace
locust/exception.py:33:80: E501 line too long (85 > 79 characters)
locust/exception.py:36:1: E302 expected 2 blank lines, found 1
locust/exception.py:38:80: E501 line too long (81 > 79 characters)
locust/exception.py:41:1: E302 expected 2 blank lines, found 1
locust/exception.py:48:1: E302 expected 2 blank lines, found 1
locust/exception.py:55:1: E302 expected 2 blank lines, found 1
```

### Describe the solution you'd like

Fix all current formatting so it's PEP8 compliant and then add a Github action to enforce it.

### PR DESCRIPTION
**Pull request by cyberw**
Fixes #1489 (kinda)

* Black is very popular, so many will be familiar with it.
* It is good at minimizing diffs
* It is very opinionated (the only config I've added is the line length), so there should be minimal discussion about how to configure it
* IMO it strikes a good balance between keeping the code nicely formatted (and PEP8 compliant) without making it unnecessarily long. 

Here's a comparison of various formatters https://medium.com/3yourmind/auto-formatters-for-python-8925065f9505

As the next step, we could (should) increase the number of rules covered by flake8 (probably switching to ignoring the few rules that we dont like instead of enabling a few favourite ones. something like --ignore E501,W503,E701,E731,E741,E712,E402,F401).

### CODE REVIEW

**Comment by max-rocket-internet** [comment]
Nice!

Does this also get checked by travis so we stop PRs that don't comply?

**Comment by cyberw** [comment]
> Nice!
> 
> Does this also get checked by travis so we stop PRs that don't comply?

Yup!

**Comment by cyberw** [comment]
@heyman Any thoughts on this? I hope you like it. I know it pollutes the git history a little but not using consistent formatting is, imo, not really an option in the long run either.

**Comment by heyman** [comment]
It's been discussed before, and my opinion hasn't changed. In many cases I think Black reduces readability, and I don't see much *real* benefit from it. 

There's a lot that can be said about Black. Some people like it, others dislike it. I fall into the second camp.

**Comment by max-rocket-internet** [comment]
If the changes in this PR are from Black, then it's still a massive improvement, no?

**Comment by cyberw** [comment]
@heyman What are your objections to Black specifically? If there is a better formatter out there then lets talk about it. 

IMO, having code with arbitrary formatting (which is currently the case) sucks really bad. For readability, diffs, etc.

**Comment by heyman** [comment]
@cyberw IMO Black decreases readability in more cases than it increases it (obviously depending on what code base you apply it to).

I don't think having 100% consistent formatting is an end in itself. Here are two examples from the very first file of this PR's diff:

* image
  This first one might be a matter of taste, but I don't like the extra indentation for the tuple. 

* image
  This one I find objectively worse. Splitting the arguments on different lines makes sense both because we're joining on a `\n` which will make the output go on different lines, and also because the inner `"\n".join(rows)` is more hidden in the one-line version.

Here are a few others (I don't have the time to go through the whole diff):

* image
  
  In these cases the lines were made intentionally short, in order for the example to fit well on the https://locust.io website (see the "With HTML parsing" example). Obviously Black - or any other auto formatter - can't know that which is also the problem with autoformatters IMO. There are contextual circumstances that's impossible to write automatic rules for.

* image
  Another example where context matters. To a human I think the non-Black version is much better.

* image
  Another very minor one (and arguably a matter of taste). To me the grouping makes sense (they are imported from different modules), but understandably not to an auto formatter.

* image
  Same here. The grouping of the short hand parameter with the long version makes sense, but it's (close to) impossible for an autoformatter to know that.

> IMO, having code with arbitrary formatting (which is currently the case) sucks really bad. For readability, diffs, etc.

I can't see why diffs would be any worse unless you start changing the formatting for pieces of code that is unrelated to your change (which is the actual problem in that case IMO). When it comes to readability, I'm all for changing the formatting of a piece of code that you find hard to read.

**Comment by cyberw** [comment]
> @cyberw IMO Black decreases readability in more cases than it increases it (obviously depending on what code base you apply it to).

I dont think you've actually given it much of a shot. If you use Black integrated in your editor for more than 30 minutes I can almost guarantee you will fall in love with it (if you were talking about yapf, which is ridiculously generous with line breaks and has other issues, I might understand what you're talking about)

> I don't think having 100% consistent formatting is an end in itself. Here are two examples from the very first file of this PR's diff: ...

I kind of agree with your examples, those are special cases where the auto formatter can't know the reasons for doing particular formatting. But I dont think they are *significantly* worse after formatting.

Having consistent formatting (Black's or some other tools) improves code readability. While a perfect manual formatting might be a little better than what an automated tool can do but that is not really an option...

>   In these cases the lines were made intentionally short, in order for the example to fit well on the https://locust.io website (see the "With HTML parsing" example). Obviously Black - or any other auto formatter - can't know that which is also the problem with autoformatters IMO. There are contextual circumstances that's impossible to write automatic rules for.

Actually that was not Black, that was me :) Black does not format comments and I'll be happy to revert that change.

> > IMO, having code with arbitrary formatting (which is currently the case) sucks really bad. For readability, diffs, etc.
> 
> I can't see why diffs would be any worse unless you start changing the formatting for pieces of code that is unrelated to your change (which is the actual problem in that case IMO). When it comes to readability, I'm all for changing the formatting of a piece of code that you find hard to read.

Diffs are primarily worse because formatting is based on the programmers preference (so there might be inadvertent changes, like with @max-rocket-internet 's issue), but also because Black does neat things like consistently inserting a comma after the last entry in a line-separated list (so that if you add an item there is no diff on the last entry)

I think the only reason to not implement *any* kind of autoformatting is if you consider Locust to be mostly finished and its git history more important than ease of future improvements.

**Comment by max-rocket-internet** [comment]
I'm 100% for any tool to help clean up the formatting and everything in this PR is an improvement IMO. Perhaps could we merge this and then if @heyman wants to use another tool or change the settings then that can come later?

> Being able to do git blame easily is a good thing, but I dont think it is worth keeping badly formatted code.

This is Github, you can get a super nice UI showing the history of any file so IMO the point about git history is moot.

This project has over 10k stars, it's 2020, let's make this project reflect this 🙏 😃

**Comment by vstepanov-lohika-tix** [comment]
Neutral solution could be using **pylint** - it is also very popular, configurable, and there are no risks with auto-formatting since all errors & warnings must be fixed manually.

**Comment by cyberw** [comment]
> Neutral solution could be using **pylint** - it is also very popular, configurable, and there are no risks with auto-formatting since all errors & warnings must be fixed manually.

We're already using flake8/pycodestyle (albeit with ridiculously permissive settings). I like pylint myself, but I think this is a separate topic.

**Comment by heyman** [comment]
> I think the only reason to not implement any kind of autoformatting is if you consider Locust to be mostly finished and its git history more important than ease of future improvements.

I actually feel the opposite. I use the git history all the time when trying to understand existing code while working on a code base (Locust included). If I knew that I didn't plan to do any future development on it, I wouldn't really care about the git history.

> This is Github, you can get a super nice UI showing the history of any file so IMO the point about git history is moot.

The history will be obfuscated on Github as well. For whitespace changes you can partly work around it by manually adding the `w=1` parameter to a lot of Github URLs (though last I checked there were pages on Github where that wasn't supported). Other formatting changes will obfuscate the git history on Github just as with other git tools.

**Comment by cyberw** [comment]
@heyman Is there anything we *could* do to fix formatting then?

To me, it feels like you have resisted every significant change suggested by someone other than yourself in the last year (removing mandatory TaskSets, dropping py2 support, constant RPS target, reintroducing request/iteration count target, default to zero wait time, etc). This is very frustrating for me.

I get that Locust is your baby and you care a lot about it. But is it possible that this is another one of those cases you might be a little too resistant to change?

IMHO, the best tool/open source project is not the one that never breaks (and definitely not the one that has a perfect git log), but the one that strikes a balance between robustness & evolution.

I'll be happy to discuss alternative approaches to solving the current formatting mess, but it seems you don't want to do anything at all...

**Comment by heyman** [comment]
@cyberw 

> To me, it feels like you have resisted every significant change suggested by someone other than yourself in the last year (removing mandatory TaskSets, dropping py2 support, constant RPS target, reintroducing request/iteration count target, default to zero wait time, etc). This is very frustrating for me.

I find that statement a bit unfair. There has been quite a few significant changes apart from the proposed ones you listed that has been merged, and for the issues you listed I think I've given reasonable arguments to why I have been hesitant. Regarding the removal of the mandatory TaskSets I think we ended up with a much better solution than the one originally proposed. 

With that said, I do think it's reasonable for a fairly mature open source project to have an initially sceptic approach to large changes. I think it has benefited Locust, and I think it has made projects such as Django successful in the long run.

> I get that Locust is your baby and you care a lot about it. But is it possible that this is another one of those cases you might be a little too resistant to change?

I don't agree with the way you've framed the question, but it's definitely possible that adopting auto formatting using Black would be net positive for Locust.

> I'll be happy to discuss alternative approaches to solving the current formatting mess, but it seems you don't want to do anything at all

I've yet to be convinced that there is a huge problem with not having a 100% formatting consistency. Apart from people's editors autoformatting files they touch (which might be solvable with a `.editorconfig` file?) I just can't see the big benefit of using an autoformatter, but i *can* see drawbacks which I've already described here (as well as in #759 and #113).

In the end I really think it comes down a lot to personal preference when it comes to using auto formatters. The best argument for me so far would be to never have to have this argument again :).

**Comment by heyman** [comment]
Also, if we were to adopt Black, maybe it would be worth waiting for a stable Black version to be released? It would include [this](https://github.com/psf/black/issues/1288) which would at least fix one of the issues I have have with the Black formatting.

**Comment by cyberw** [comment]
> I've yet to be convinced that there is a huge problem with not having a 100% formatting consistency.

Having perfect consistency is not the issue, having *reasonable* consistency is. I dont know a of a good way to keep any kind of consistency without using some kind of opinionated auto formatter (except using an opinionated linter & doing it manually but that is much more work)

> In the end I really think it comes down a lot to personal preference when it comes to using auto formatters. The best argument for me so far would be to never have to have this argument again :)

Haha... If that tips the scale, I'll take it ;)

> Also, if we were to adopt Black, maybe it would be worth waiting for a stable Black version to be released? It would include this which would at least fix one of the issues I have have with the Black formatting.

Yea, a fix for that would be nice. Looking at pypi, it seems all Black-releases are pre-releases so I wouldnt wait for a stable one (I think this is intentional, but I dont know why they do it)

Unfortunately (and this worries me a little now) there hasnt been a release since October 2019. Maybe we should hold back a little and see if the project has fallen asleep... we dont want to start using Black just to have to switch to something else later on.

**Comment by cyberw** [comment]
Hmm. The issue you mentioned is actually supposed to work in 19.10b0 (according to the comments in the issue at least). What is the case you are seeing? Maybe I just need to add a trailing comma?

**Comment by heyman** [comment]
> What is the case you are seeing? Maybe I just need to add a trailing comma?

This one, for example:

image

**Comment by cyberw** [comment]
> > What is the case you are seeing? Maybe I just need to add a trailing comma?
> 
> This one, for example:

Ok, yea, looking closer at the conversation in the issue I see that nested collections is not yet fixed. Not sure if it will be fixed any time soon, but I guess we could hold off for a while if a fix for that would help convince you that the change is "net-positive".

**Comment by cyberw** [comment]
I'll close this for now. But once magic commas for nested collections are fixed, I'll be back :)

**Pull request closed without merging**
