### PR TITLE
Remove unused imports

### PR DESCRIPTION
**Pull request by mbeacom**
This PR removes unused imports and exception assignments throughout the project.

*Removed whitespace trimming per @cgoldberg's request.*

### CODE REVIEW

**Comment by cgoldberg** [comment]
@mbeacom please remove those whitespace changes (sorry, same thing happened with my editor) so the PR only contains your code changes.  We will deal with the whitespace removal in separate PR's.  I can re-review once you update.  thanks!

**Comment by cgoldberg** [comment]
@mbeacom thanks!

I just scanned your branch and it looks like there are still a few unused imports left.  Can you remove those also in this PR?  They occur in these 3 files:
 * `/locust/__init__.py`
 *  `/locust/test/test_locust_class.py`
 * `/examples/custom_xmlrpc_client/server.py`
 *  `/locust/rpc/__init__.py`

flake8 scan results:
```
(unused-imports)$ flake8 | grep "imported but unused"
./locust/__init__.py:1:1: F401 '.core.HttpLocust' imported but unused
./locust/__init__.py:1:1: F401 '.core.task' imported but unused
./locust/__init__.py:1:1: F401 '.core.TaskSet' imported but unused
./locust/__init__.py:1:1: F401 '.core.Locust' imported but unused
./locust/__init__.py:2:1: F401 '.exception.ResponseError' imported but unused
./locust/__init__.py:2:1: F401 '.exception.RescheduleTaskImmediately' imported but unused
./locust/__init__.py:2:1: F401 '.exception.InterruptTaskSet' imported but unused
./locust/test/test_locust_class.py:405:9: F401 'locust.stats.RequestStats' imported but unused
./locust/rpc/__init__.py:7:5: F401 '.socketrpc as rpc' imported but unused
./locust/rpc/__init__.py:9:1: F401 '.protocol.Message' imported but unused
./examples/custom_xmlrpc_client/server.py:4:1: F401 'xmlrpclib' imported but unused
```

**Comment by mbeacom** [comment]
@cgoldberg Thanks for your time! I have made the requested changes to the test and example files I missed in my update.  I didn't remove the imports from the `__init__.py` files because it seems we are using them in some cases.  i.e.:  [`locust/runners.py#L19`](https://github.com/locustio/locust/blob/master/locust/runners.py#L19)

Would you like me to refactor to remove the need for these init imports?

**Comment by cgoldberg** [comment]
> Would you like me to refactor to remove the need for these init imports?

I'm going to merge this as-is... any refactoring can be done in another PR.

**Comment by cgoldberg** [comment]
Thanks for the contribution!
:+1:

**Pull request merged**
