### PR TITLE
Major rework of documentation & many small fixes

### PR DESCRIPTION
**Pull request by cyberw**

### CODE REVIEW

**Comment by cyberw** [comment]
@max-rocket-internet @phil-davis Could you have a look thru the documentation for any obvious errors? 

It would be good with at least one more set of eyes on it before release.

https://docs.locust.io/en/latest/ 

Thanks!

**Comment by phil-davis** [comment]
Looks OK - see #1528 
I didn't see obvious errors. I will find those when I do trickier load-testing and actually try more of the examples ;)

**Comment by max-rocket-internet** [comment]
Looks good to me.

I would dress up the main repo README.md a bit though. IMO it doesn't show the best things about locust very clearly. It could be much nicer with a simple locust file example and screen shot of the UI. Shall I create a PR?

**Comment by cyberw** [comment]
Great idea, please do!

**Comment by cyberw** [comment]
I went ahead with the release! (but I would still love an updated readme - it's not really part of the release anyway)

**Pull request merged**
