### PR TITLE
Introduce docs for increasing the max number of open files limit

### PR DESCRIPTION
**Pull request by ericandrewlewis**

### CODE REVIEW

**Comment by cgoldberg** [comment]
:+1:

**Comment by heyman** [comment]
Great! Thanks!

**Comment by aidylewis** [comment]
Should we also describe how the open file limit can be increased in Linux through /etc/sysctl.conf (system wide limit)? And should we also mention about increasing ephemeral ip ports?

**Comment by aidylewis** [comment]
I've got this for Fedora based Linux

```sh
# increase system file descriptor limit
echo fs.file-max = 100000 | sudo tee /etc/sysctl.conf
# increase ulimit ( < system file descriptor )
printf '*       soft    nofile  99999 \n*       hard    nofile  99999' | sudo tee /etc/security/limits.conf
```
Also, need to reboot.

For Debian based, I think you also need to enable PAM user limits.

**Pull request merged**
