### PR TITLE
Keep csv files open

### PR DESCRIPTION
**Pull request by lhupfeldt**
The intent of is to reduce os calls and disk IO.
This code goes on top of my other PR https://github.com/locustio/locust/pull/1504, so submitting as draft.

### CODE REVIEW

**Comment by cyberw** [comment]
Does this also split stats into stats and stats_csv? It might make sense, but as I dont really know the web interface code very well, I can't really judge if that is a good idea.

**Comment by lhupfeldt** [comment]
> Does this also split stats into stats and stats_csv? It might make sense, but as I dont really know the web interface code very well, I can't really judge if that is a good idea.

Yes, it splits out the csv generation. I think it gives better readability, but I can merge it back into stats if you prefer.

**Comment by cyberw** [comment]
Is this ok to merge now?

**Comment by lhupfeldt** [comment]
Let me rebase on master first.

**Comment by cyberw** [comment]
Good to go?

**Comment by lhupfeldt** [comment]
> ~Good to go?~ oh right, still waiting to un-split stats/stats_csv (preferably by rewriting the history so that git-blame is not distorted)

I think I will be to blame for the stats-csv stuff regardless how it is un-split, since all lines will be indented under the class.
So the easiest will be to simply copy stats_csv content back into stats.
Any objection to that?

**Comment by lhupfeldt** [comment]
Created a new single commit and force pushed, should keep the blame changes to a minimum, although not sure there is much difference.

**Comment by cyberw** [comment]
LGTM. Thanks!

**Pull request merged**
