### PR TITLE
Added response.ok support to FastHttpUser's FastResponse class simila…

### PR DESCRIPTION
**Pull request by PankajKhanwani**
…r to HttpUser's Response

### CODE REVIEW

**Comment by cyberw** [comment]
Nice!

**Comment by cyberw** [comment]
Huh. Seems this only fixes it for direct calls, not for ResponseContextManager. So the following still doesnt work for FastHttpUser. Can you take a look?

```
with self.client.get("/", catch_response=True) as resp:
    print(resp.ok)
```

**Comment by PankajKhanwani** [comment]
class FastTestUser(FastHttpUser):
    host = "https://example.com"

    @task
    def get(self):
        with self.client.get("/", catch_response=True) as resp:
            print(resp.__class__)
            print(resp.ok)
            
Output:
`<class 'locust.contrib.fasthttp.ResponseContextManager'>
True
`

**Comment by cyberw** [comment]
Sorry, my bad. I must have accidentally been on a branch or something..

**Pull request merged**
