### PR TITLE
Optimize `SequentialTaskSet`

### LINKED ISSUE #2739: `SequentialTaskSet` handles task weights in an inconsistent way
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

Currently, `SequentialTaskSet` does not allow its `tasks` attribute to be a dict, and throws the following error:

```
if isinstance(value, list):
     new_tasks.extend(value)
else:
     raise ValueError("On SequentialTaskSet the task attribute can only be set to a list")
```

However, if they weight is provided to the `@task` decorator, the tasks are actually repeated in the task list according to the weight:

```
if "locust_task_weight" in dir(value):
      # method decorated with @task
      for _ in range(value.locust_task_weight):
            new_tasks.append(value)
```

This is inconsistent.
It should be possible to provide task weights also in a dict, with similar repeated insertion into the list.
(Few would probably use it like that, but it removes the inconsistency).

### LINKED ISSUE #2740: Use `itertools.cycle` in `SequentialTaskSet`
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

### Description

Currently, `SequentialTaskSet.get_next_task` uses an index and module operation to loop over the same list in a cycle https://github.com/locustio/locust/blob/c6665d41164534120d62bdeb7eba99e4e10771ac/locust/user/sequential_taskset.py#L62

It should be easy to replace this with `itertools.cycle`, which is a built in memory-efficient iterator for creating cycles over iterables.

### PR DESCRIPTION
**Pull request by bakhtos**
Fixes #2739 
Fixes #2740 

As explained in respective issues,`SequentialTaskSet` now allows task repetition if `tasks` is a dictionary with weight, and `itertools.cycle` is used to iterate over tasks in a cycle.

So far only a draft of backend changes.

Let me know if changes are OK and then I will update also tests and docs.

### CODE REVIEW

**Comment by cyberw** [comment]
Looks good to me, apart from the import sorting. Run `ruff` and/or install pre-commit hook (https://pre-commit.com/) to make formatting/checks happen automatically on commit!

I dont use SequentialTaskSets personally, so if there's an issue in the future I might ping you :)

**Comment by bakhtos** [comment]
@cyberw Okay, I will fix the build shortly. Another question, though - should I add tests for the `tasks` being a dictionary in `SequentialTaskSet`?

**Comment by cyberw** [comment]
> @cyberw Okay, I will fix the build shortly. Another question, though - should I add tests for the `tasks` being a dictionary in `SequentialTaskSet`?

Yes, I think that would be nice!

**Comment by cyberw** [comment]
Hi @bakhtos ! Are we ready to take this out of draft status? Maybe once you’ve updated the docs?

**Comment by bakhtos** [comment]
@cyberw Turned out few modifications to the documentation were necessary, this is now ready

**Comment by cyberw** [comment]
Is the updated PR name ok with you?

**Pull request merged**
