### PR TITLE
Update Web UI About box

### PR DESCRIPTION
**Pull request by cyberw**

### CODE REVIEW

**Comment by cyberw** [comment]
LGTY @andrewbaldwin44 ? (as in: did I make any horrible mistakes? :)

**Comment by andrewbaldwin44** [comment]
Looks super nice to me! :+1:

**Comment by andrewbaldwin44** [comment]
Not enough border on dark mode or too dark?

**Comment by cyberw** [comment]
I think my screen is a little bad and crushes all the blacks :)

Maybe the background needs to be slightly lighter?

**Comment by cyberw** [comment]
Hehe, resetting my screen settings to default made it much more visible (although it is nice to cater to people with semi-broken screens too :)

**Comment by cyberw** [comment]
Haha, yea I guess you're right. No need to put it at the top of your list or anything :)

**Pull request merged**
