### PR TITLE
Add distribution and request csvs to commandline usage.

### PR DESCRIPTION
**Pull request by cpennington**
Original-Author: Kevin Peter Savage (https://github.com/kevinpetersavage)

This is based on https://github.com/locustio/locust/pull/48, rebased onto master, and with the suggestions form that PR incorporated.

### CODE REVIEW

**Comment by cpennington** [comment]
This now depends on #257

**Comment by wearp** [comment]
+1 Really useful feature. It would be great to see it merged.

**Comment by wiebren** [comment]
+1

For those waiting for this to integrating Locust in your CI and want a workaround in the meantime. I created a simple wrapper that saves the results in a MonKit file. We use it in combination with the MonKit plugin for Jenkins to graph results. 

https://gist.github.com/wiebren/72ae7a9421520aa77fac

**Comment by Benoss** [comment]
This feature would be awesome, maybe a json output would be nice as well

**Comment by JohannesRudolph** [comment]
+1

**Comment by MatMoore** [comment]
What needs to happen to get this merged? @heyman does this address your comments in #48?

**Comment by cpennington** [comment]
@cgoldberg: This is rebased and should be merge-able now

**Comment by sj2208** [comment]
@cgoldberg - when will this be merged ?

**Comment by sherif84** [comment]
any updates/ETA on this  merge ?

**Comment by Jiff21** [comment]
Should this be closed in favor of https://github.com/locustio/locust/pull/445

**Comment by aldenpeterson-wf** [comment]
@Jiff21 probably in favor of https://github.com/locustio/locust/pull/612

**Comment by mbeacom** [comment]
Closed in favor of #612 (merged) - Thank you!

**Pull request closed without merging**
