### PR TITLE
Allow overriding redirect response codes for FastHttpLocust

### PR DESCRIPTION
**Pull request by cyberw**
Adresses #1238

### CODE REVIEW

**Comment by heyman** [comment]
I wonder if it wouldn't be better to add an `allow_redirects` argument to the `FastHttpSession.request()` method (and `get()`, `post()`, etc.), and  dynamically set the `redirect_resonse_codes` to `[]` if `allow_redirects` is set to `False`?

That way we we would get the same API as the Requests client, and one wouldn't have to choose between turning off/on redirects for *all* requests.

**Comment by cyberw** [comment]
> I wonder if it wouldn't be better to add an `allow_redirects` argument to the `FastHttpSession.request()` method (and `get()`, `post()`, etc.), and dynamically set the `redirect_resonse_codes` to `[]` if `allow_redirects` is set to `False`?
> 
> That way we we would get the same API as the Requests client, and one wouldn't have to choose between turning off/on redirects for _all_ requests.

How’s about I do both?

**Comment by heyman** [comment]
> How’s about I do both?

If we have `allow_redirects` I actually don't really see the need for being able to set `redirect_resonse_codes` for the session instance. Seems like such an uncommon edge case?

**Comment by cyberw** [comment]
> > How’s about I do both?
> 
> If we have `allow_redirects` I actually don't really see the need for being able to set `redirect_resonse_codes` for the session instance. Seems like such an uncommon edge case?

Damn, you are right. Not a lot of people will be used to geventhttpclient properties anyway. Ok, will fix.

**Pull request closed without merging**
