### PR TITLE
make user count available to LoadTestShape

### PR DESCRIPTION
**Pull request by msarahan**
Related to #1715

### CODE REVIEW

**Comment by msarahan** [comment]
Here's a screenshot of running the example. The notable features are the plateaus at the 10, 20, and 10 user levels. We don't know what time it'll take to get there, but once we are there, we always sit there for the given pre-set time.

Screenshot from 2021-03-01 09-34-16

**Comment by cyberw** [comment]
Can you add a unit test?

**Comment by msarahan** [comment]
I should probably also update the docs at https://docs.locust.io/en/latest/generating-custom-load-shape.html#generating-custom-load-shape to show this new function. I'll work on that a bit later.

**Comment by cyberw** [comment]
This looks good. Can you make runner a regular attribute (not _-prefixed). Maybe people will want to access some other attribute on the runner.

**Comment by cyberw** [comment]
nice!

**Comment by msarahan** [comment]
Thanks for working with me on this. I'll close the other issue.

**Pull request merged**
