### PR TITLE
Bump geventhttpclient and switch back to use its original repo 

### PR DESCRIPTION
**Pull request by cyberw**
... instead of its fork, now that there is a new release (I can trigger new releases later on as well). Relates to #1116

### CODE REVIEW

**Comment by heyman** [comment]
Before we can merge this we need to update the geventhttpclient repo and setup building + uploading of wheels for both Linux, Mac and Windows. For Windows I think we need to use Appveyor. This has already been done for the forked repo (https://github.com/locustio/geventhttpclient), so we should be able to take the changes from there. If we merge this without binary wheels available for common platforms it would cause installation of Locust to fail for people who don't have a build environment set up with the necessary lib dependencies installed.

**Comment by cyberw** [comment]
I’ll have a look

**Comment by cyberw** [comment]
Ok, super confusing. I can see we've uploaded the windows build in the log https://ci.appveyor.com/project/cyberw/geventhttpclient/builds/33063424 but in pypi there is no windows build :-/

**Comment by heyman** [comment]
> My guess is that APPVEYOR_REPO_TAG is not true, but I cant understand why. It may be related to the fact that builds are not triggered automatically (I have to do it manually)

That sounds plausible. Are you lacking permissions to set up the triggers? If so I guess @gwik has to set it up or give us admin access. I guess an alternative could be to see if he'd be okay with moving the official geventhttpclient repo over to the locustio org?

**Comment by gwik** [comment]
As I said before I have no issue moving the repo wherever there are people willing to maintain it.

**Comment by gwik** [comment]
Just let me know what you need.

**Comment by cyberw** [comment]
I think it it least disruptive to keep it where it is (but moving it is also fine I guess). I guess you have given us all the permissions you can with the repo itself @gwik ? Maybe appveyor needs to be added to the project level?

**Comment by cyberw** [comment]
I changed appveyor to always try uploading, even when it doesnt detect a tag, so we now should have a good 1.4.2 package! (I still need to push a button on appveyor to get the windows wheel out, but that is acceptable for now)

**Comment by cyberw** [comment]
Tested on windows and it works (found a bug while I was at it). Merging this, but we can continue discussing here if you want :)

**Comment by heyman** [comment]
> Tested on windows and it works (found a bug while I was at it). Merging this, but we can continue discussing here if you want :)

Great work!

We should still try to get automatic triggering to work I think so that windows releases aren't forgotten a few years down the line :).

**Pull request merged**
