### PR TITLE
Added an event to specifically signal when a test is stopped (either …

### PR DESCRIPTION
**Pull request by SandyChapman**
…on quit or when the stop button is pressed).

Based on code / comments in https://github.com/locustio/locust/pull/278

### CODE REVIEW

**Comment by mbeacom** [comment]
@SandyChapman Are you still interested in having this PR reviewed?

**Comment by piontkowski** [comment]
+1 for this. Was just chatting today with a colleague that we would love to tap into a stop event.

**Comment by mbeacom** [comment]
@piontkowski I would resolve the conflicts, but this PR was submitted before collaborator conflict resolution was introduced.  If someone resolves the conflicts or submits another PR for this feature, I will review and merge it!

**Comment by SandyChapman** [comment]
@piontkowski @mbeacom : I'd like to move forward with this, but it's difficult to find time at the moment. I'm not overly familiar with the GitHub process, but if someone wants permissions to the source repo, let me know and I'll add them.

**Comment by SandyChapman** [comment]
@piontkowski @mbeacom : After looking at the PR, this was much less code than expected. I've resolved the conflicts, but haven't tested the changes.

**Comment by shanaka-m** [comment]
+1. Before we got to see this PR, we were doing the cleanup stuff manually. Now we are using this as a teardown method. This is a must-have feature. Thank you @SandyChapman !

**Comment by cyberw** [comment]
Hi! This PR has been untouched for a very long time and has conflicts so I am closing it. Let me know if this was a mistake and feel free to open it again.

**Pull request closed without merging**
