### PR TITLE
Confidence intervals

### PR DESCRIPTION
**Pull request by cpennington**
This adds confidence intervals to percentile reports (if the extra `[scipy]` requirements are installed).

### CODE REVIEW

**Comment by cpennington** [comment]
This depends on #257

**Comment by cpennington** [comment]
@cgoldberg: This has been rebased, and is ready to be merged.

**Comment by mbeacom** [comment]
Does this already include the changes from #257 ?

**Comment by cyberw** [comment]
Hi @cpennington ! This PR was never merged and now has conflicts. Please reopen it & fix the conflicts if you still care about it!

**Pull request closed without merging**
