### PR TITLE
Fix and add test for when locusts fail to exit at end of iteration during stop timeout.

### PR DESCRIPTION
**Pull request by cyberw**
I discovered a bug introduced in the last commit on stop-timeout. Adding a test case for it (and once you have seen that it actually fails), I will revert that commit to show that it now works :)

### CODE REVIEW

**Comment by heyman** [comment]
Ah, I see, my bad! Could we move the check from the `wait()` method to immediately after `self.execute_next_task()` instead?

**Comment by cyberw** [comment]
> Ah, I see, my bad! Could we move the check from the `wait()` method to immediately after `self.execute_next_task()` instead?

You mean after line 365? That doesnt work, because it wont be called on interrupts.

**Comment by cyberw** [comment]
> > Ah, I see, my bad! Could we move the check from the `wait()` method to immediately after `self.execute_next_task()` instead?
> 
> You mean after line 365? That doesnt work, because it wont be called on interrupts.

Wait, I get it now, you meant move the *other* check. Yes, that works, and arguably makes more sense. Commiting it now...

**Comment by cyberw** [comment]
Always running one iteration when using stop-timeout should be fine imo (maybe even desirable). I'll can definitely add it, but I dont think it is worth bloating the code.

**Comment by heyman** [comment]
Nice! LGTM?

**Pull request merged**
