### PR TITLE
Rename hatch rate to spawn rate. Fixes #1405

### LINKED ISSUE #1405: rename "hatch rate" to "spawn rate"
More standard terminology, plus the word "hatching" doesnt make sense any more, now that Locust classes are called User classes. If approved, I can make a PR.

### PR DESCRIPTION
**Pull request by cyberw**

### CODE REVIEW

**Comment by lhupfeldt** [comment]
Instead of failing when --hatch-rate is used there should be a deprecation warning and the fail should not happen until release 2.0.

**Comment by lhupfeldt** [comment]
index.html still says hatch

**Comment by cyberw** [comment]
I dont really see a big benefit of deprecating things for any significant amount of time, so I couldnt really be bothered. Maybe I should make the next release be called 2.0 though, just to be clear that it contains breaking changes.

Good catch on index.html, fixing that now.

**Comment by cyberw** [comment]
Meh. But you are right. I will deprecate it for a while instead.

**Pull request merged**
