### PR TITLE
#1832 Displaying locustfile and tasks ratio information on index.html

### PR DESCRIPTION
**Pull request by tyge68**
As discribed on #1832 , here is the suggested changes to allow displaying a bit more information about the current locustfile / tasks that will be executed in the Web UI.

About the look n feel any suggestions to make it looks nicer would be welcome.

Note this is a new PR as I had to rework my commits and so did hard push on my existing fork.

Tests are updated to match the new html title and other html output expected.

Can you please verify this one @cyberw  ?

### CODE REVIEW

**Comment by tyge68** [comment]
Screenshot mentioning currently used script filename in the title of the browser tab:
Screenshot 2021-09-01 at 11 09 57

Screenshot showing the tasks description , and script filename used.
Screenshot 2021-09-01 at 11 10 08

Screenshot showing the tasks description , and script filename used in the report html.
Screenshot 2021-09-01 at 11 09 19

**Comment by cyberw** [comment]
LGTM! Would you mind moving the Tasks tab two steps to the right, between Exceptions and Download?

**Comment by tyge68** [comment]
@cyberw just did in commit 8833ddb , let me know if that works for you.

**Comment by cyberw** [comment]
Thx!

**Pull request merged**
