### PR TITLE
Add thresholds to each request

### PR DESCRIPTION
**Pull request by JavierUhagon**
This PR adds an argument to each request to add a threshold to it, if a request response time is over the threshold it'll be logged

This also adds a new stat in the webui (the threshold) that's hidden if there are no thresholds defined.
<details><summary>Images</summary>
<p>

image

image

</p>
</details> 

Related issue: #2668 

I want to know if @cyberw thinks this can be added to the core (and it's being done nicely) before I resume my work on it!

### CODE REVIEW

**Comment by cyberw** [comment]
Hi! I do see the point in having this, but complicating HttpSession in for what is kind of a rare case doesnt make sense, it needs to be a subclass or something (side note: what are those print statements about? :)

**Comment by JavierUhagon** [comment]
> Hi! I do see the point in having this, but complicating HttpSession in for what is kind of a rare case doesnt make sense, it needs to be a subclass or something (side note: what are those print statements about? :)

I think a subclass would make sense, yeah, this is just a draft, whenever the PR is ready for review I'll remove the print statements! :)

Kk, I'll work on that and @ you whenever it's ready!

**Comment by JavierUhagon** [comment]
@cyberw I've added a new HttpSession subclass for this, and to use this there is a new HttpUser, if you think this can or should be done differently let me know!

**Comment by cyberw** [comment]
Hi Javier! So sorry for the late response, things have been crazy lately. I understand the need for this, but the changes in stats.py are a little too big for a feature that will only rarely be needed. I think for now I'll have to suggest the workaround of marking requests as failed when they exceed your threshold https://docs.locust.io/en/stable/writing-a-locustfile.html#validating-responses

**Comment by JavierUhagon** [comment]
Okay, that's fair enough, I'm not sure if you want me to close the PR or change my modifications and add an easy way to check the thresholds (even if we just fail the request!)

**Comment by cyberw** [comment]
I'll close this. If you want to make it easier for other people to find the fail-request-on-bad-response time, maybe we could add it to one of the locustfile examples?

**Pull request closed without merging**
