### PR TITLE
Ability to hide extra args from web ui

### LINKED ISSUE #1876: Ability to explicitly set which arguments will be exposed/visible in the web ui
### Is your feature request related to a problem? Please describe.
All custom arguments are shown in the web UI

```python
@events.init_command_line_parser.add_listener
def _(parser):
    parser.add_argument("--a1", type=str, env_var="MYAPP_A1", default="a1_value", help="a1 help")
    parser.add_argument("--a2", type=str, env_var="MYAPP_A2", default="a2_value", help="a2 help")
    parser.add_argument("--a3", type=str, env_var="MYAPP_A3", default="a3_value", help="a3 help")
    parser.add_argument("--a4", type=str, env_var="MYAPP_A4", default="a4_value", help="a4 help")
    parser.add_argument("--a5", type=str, env_var="MYAPP_A5", default="a5_value", help="a5 help") 
```
Screenshot from 2021-09-06 15-18-08

### Describe the solution you'd like
Ability to explicitly set which arguments will be exposed/visible in the web ui.

Perhaps a new flag ?
 ```
 --web_hide_extra_args=a4,a5
 ```

Or a new param to `add_argument`:

```python
@events.init_command_line_parser.add_listener
def _(parser):
    parser.add_argument("--a1", type=str, env_var="MYAPP_A1", default="a1_value", help="a1 help")
    parser.add_argument("--a2", type=str, env_var="MYAPP_A2", default="a2_value", help="a2 help")
    parser.add_argument("--a3", type=str, env_var="MYAPP_A3", default="a3_value", help="a3 help")
    parser.add_argument("--a4", type=str, env_var="MYAPP_A4", default="a4_value", help="a4 help", exclude_from_ui=True)
    parser.add_argument("--a5", type=str, env_var="MYAPP_A5", default="a5_value", help="a5 help", exclude_from_ui=True) 
```

### Describe alternatives you've considered
ATM I am removing the options from CLI and just reading them directly from env variables.

### PR DESCRIPTION
**Pull request by fabito**
Resolves #1876

### CODE REVIEW

**Comment by cyberw** [comment]
After looking at your code more closely, I think it would be preferable to store the flag *on* the action itself (instead of in a separate list) 

Is that possible?

**Comment by fabito** [comment]
We probably can.
Regardless where we decide to store it (indeed in the Action seems a better option), I think we will still need access to the parser instance I know how to propagate action metadata to the  `parsed_options`.|

**Comment by cyberw** [comment]
One question: is it be possible to hide/unhide an argument after the fact?

And maybe we should invert the parameter? (change it to include_in_web_ui, default to True). What do you think?

**Comment by fabito** [comment]
Yeah, we can invert the flag, no problem.
What do you mean by "after the fact" ? Can you give me an example ?

**Comment by cyberw** [comment]
> What do you mean by "after the fact" ? Can you give me an example ?

Lets say a library, like locust-plugins, or some shared file that you import in all your locust files adds a parameter that is hidden (or visible) in the web UI, and you want to show it (or hide it).

e.g (in your library)

    parser.add_argument("--my-ui-invisible-argument", include_in_web_ui=False, default="I am invisible")

and then in your specific locustfile, it would be nice to be able to override that, by doing something like this:

    parser.my_ui_invisible_argument.include_in_web_ui = True

**Comment by fabito** [comment]
I am not an `ArgumentParser` expert but AFAIK it does not expose an API for changing or removing arguments. 
Since `include_in_web_ui` does not affect the parsing logic we could add a function that locates the action ( `_actions` attribute ) and change the flag's value.

Maybe something like this ??

```python
def include_in_web_ui(self, arg):
    for action in self._actions:
        if (vars(action)['option_strings']
            and vars(action)['option_strings'][0] == arg) \
                or vars(action)['dest'] == arg:
            action.include_in_web_ui = True
            return

    for action in self._action_groups:
        vars_action = vars(action)
        var_group_actions = vars_action['_group_actions']
        for x in var_group_actions:
            if x.dest == arg:
                x.include_in_web_ui = True
                return
```

**Comment by cyberw** [comment]
That looks complicated, but it is an acceptable limitation not to be able to modify it. Thanks for the PR!

**Pull request merged**
