### PR TITLE
Add "stopping" state.

### PR DESCRIPTION
**Pull request by solowalker27**
Fixes https://github.com/locustio/locust/issues/981

### CODE REVIEW

**Comment by Eadword** [comment]
Looks good to me. Tested working on my setup.

**Comment by mangatmodi** [comment]
I saw the code and it should work, but I am trying to think why this is introduced.

here - https://github.com/locustio/locust/blob/68ac9d3eef6d43f76451b53f00acc1a2a5ab9de9/locust/runners.py#L436
Client on being stop sends `client_ready` message. On receiving `client_ready` now we hatch the client
https://github.com/locustio/locust/blob/68ac9d3eef6d43f76451b53f00acc1a2a5ab9de9/locust/runners.py#L346
Which was added in recent commit - https://github.com/locustio/locust/commit/15499297cd04b90275d3ee4a59a1068ad739b53b

Client is now in `HATCHING` state - https://github.com/locustio/locust/blob/68ac9d3eef6d43f76451b53f00acc1a2a5ab9de9/locust/runners.py#L426

With a bit of bad luck(or enough number of runs), server might receive one of the client as hatching and hence the condition is always false - 
https://github.com/locustio/locust/blob/68ac9d3eef6d43f76451b53f00acc1a2a5ab9de9/locust/runners.py#L374

Adding  `STOPPING` works as it will avoid hatching the clients, no matter the status. It seems good enough, but I see the problem when a client is stopped, it shouldn't be ready.

**Comment by mangatmodi** [comment]
I think it is ready because master can send another test request, After stopping one. That also means the heartbeat should continue even when client is stopped :)

**Comment by wincus** [comment]
validated that this fixed the issue on our setup as well. Thanks!

**Comment by tsykora-verimatrix** [comment]
glad to see this fixed, good job, is it going to be part of 0.12.0 or how it will be released?

**Pull request merged**
