### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by pmdarrow**
Added support for Python 3 and running tests against all supported versions of Python with tox. 

Borrowed heavily from https://github.com/locustio/locust/pull/328 but cleaned things up & simplified some changes in the hopes that it will be more likely to be merged.

### CODE REVIEW

**Comment by pmdarrow** [comment]
@locustio @heyman @HeyHugo @cgbystrom @Jahaja Can you take a quick look at this and consider merging it? All the legwork has been put in and it shouldn't require much time to review.

**Comment by cgoldberg** [comment]
i'm doing a code review now.  I'm not a maintainer, but I've contributed to locust before and I watch the project.  Do the current maintainers need any help?

@pmdarrow fwiw, the tests all pass for me locally against your branch (Ubuntu 15.04).
I also tried with python 3.5 and all tests pass.  Could you add 3.5 to your tox.ini and setup.py?

**Comment by pmdarrow** [comment]
Will do. What do you think about adding 3.1, 3.2, and 3.3? Is that overkill
/ unnecessary?

**Comment by cgoldberg** [comment]
I have 3.2, and 3.3 also installed here...  so I'll add those to tox.ini and run the tests again.  Those versions seem reasonable to add to your setup.py and tox.ini...
... I'd skip 3.0/3.1, nobody uses them  :)
 (eventually, I'd imagine dropping 2.6 and 3.2 support)

 afaik, travis supports 3.2+, so we get CI on those  versions for nothing.

**Comment by pmdarrow** [comment]
I updated `setup.py`, `tox.ini`, and `travis.yml` with 3.2, 3.3 and 3.5.

**Comment by pmdarrow** [comment]
Looks like Flask doesn't support 3.2 (and the tests fail) so I'm dropping support for it.

**Comment by pmdarrow** [comment]
It appears that the Travis builds are running on legacy infrastructure that doesn't have Python 3.5 installed, so the build failure can probably be ignored.

**Comment by OPpuolitaival** [comment]
I tried this PR with --no-web and there is no more reports visible in command line during the run. There is error in logs: ' AttributeError : 'StdOutWrapper' object has no attribute 'flush'.

**Comment by smrpr** [comment]
@locustio what about this?

**Comment by pmdarrow** [comment]
@ogabrielson I'll take a look. It's too bad there aren't any automated tests for that feature...

**Comment by deniscostadsc** [comment]
Does anybody need a help to review this PR and then merge it to master?

**Comment by pmdarrow** [comment]
@deniscostadsc see https://github.com/locustio/locust/issues/355

**Comment by justiniso** [comment]
@pmdarrow I'd consider this PR the highest priority aside from any major bug fixes that come up. I'm in the process of reviewing/testing, but I found a couple of minor issues that mean it is not yet ready for merging. I think what we should do is merge your branch into a branch in this repository that we would all have access to.

**Comment by deniscostadsc** [comment]
@justiniso, could you list the issues?

**Comment by justiniso** [comment]
Yep, sorry!

Stdout no-ops: https://github.com/locustio/locust/commit/548ffe7f5e74260a50eace12469afe07acd497ca
Gevent to 1.1.0: https://github.com/locustio/locust/commit/f162e1ea2b3c6d7ce9676583bb5d6e1c568c0233

I updated gevent version to their officially supported version (rather than release candidate). Note that 3.5 is not supported and consequently we should not support it either (3.4 is the latest supported). Even with 3.4, I'm getting this error when trying to start up the slave:

```
[2016-03-30 04:01:25,604] vagrant-ubuntu-trusty-64/INFO/locust.main: Starting Locust 0.7.3
[2016-03-30 04:01:25,605] vagrant-ubuntu-trusty-64/ERROR/locust.runners: Connection lost to master server. Aborting...
[2016-03-30 04:01:25,624] vagrant-ubuntu-trusty-64/ERROR/stderr: Traceback (most recent call last):
[2016-03-30 04:01:25,624] vagrant-ubuntu-trusty-64/ERROR/stderr: File "/usr/local/bin/locust", line 9, in <module>
[2016-03-30 04:01:25,625] vagrant-ubuntu-trusty-64/ERROR/stderr: 
[2016-03-30 04:01:25,625] vagrant-ubuntu-trusty-64/ERROR/stderr: load_entry_point('locustio==0.7.3', 'console_scripts', 'locust')()
[2016-03-30 04:01:25,625] vagrant-ubuntu-trusty-64/ERROR/stderr: 
[2016-03-30 04:01:25,626] vagrant-ubuntu-trusty-64/ERROR/stderr: File "/vagrant/locust/main.py", line 442, in main
[2016-03-30 04:01:25,627] vagrant-ubuntu-trusty-64/ERROR/stderr: 
[2016-03-30 04:01:25,627] vagrant-ubuntu-trusty-64/ERROR/stderr: main_greenlet.join()
[2016-03-30 04:01:25,627] vagrant-ubuntu-trusty-64/ERROR/stderr: 
[2016-03-30 04:01:25,628] vagrant-ubuntu-trusty-64/ERROR/stderr: File "/usr/local/lib/python3.4/dist-packages/gevent-1.1.0-py3.4-linux-x86_64.egg/gevent/pool.py", line 527, in join
[2016-03-30 04:01:25,628] vagrant-ubuntu-trusty-64/ERROR/stderr: 
[2016-03-30 04:01:25,629] vagrant-ubuntu-trusty-64/ERROR/stderr: self._empty_event.wait(timeout=timeout)
[2016-03-30 04:01:25,629] vagrant-ubuntu-trusty-64/ERROR/stderr: 
[2016-03-30 04:01:25,629] vagrant-ubuntu-trusty-64/ERROR/stderr: File "/usr/local/lib/python3.4/dist-packages/gevent-1.1.0-py3.4-linux-x86_64.egg/gevent/event.py", line 213, in wait
[2016-03-30 04:01:25,629] vagrant-ubuntu-trusty-64/ERROR/stderr: 
[2016-03-30 04:01:25,630] vagrant-ubuntu-trusty-64/ERROR/stderr: return self._wait(timeout)
[2016-03-30 04:01:25,630] vagrant-ubuntu-trusty-64/ERROR/stderr: 
[2016-03-30 04:01:25,630] vagrant-ubuntu-trusty-64/ERROR/stderr: File "/usr/local/lib/python3.4/dist-packages/gevent-1.1.0-py3.4-linux-x86_64.egg/gevent/event.py", line 123, in _wait
[2016-03-30 04:01:25,631] vagrant-ubuntu-trusty-64/ERROR/stderr: 
[2016-03-30 04:01:25,631] vagrant-ubuntu-trusty-64/ERROR/stderr: gotit = self._wait_core(timeout)
[2016-03-30 04:01:25,631] vagrant-ubuntu-trusty-64/ERROR/stderr: 
[2016-03-30 04:01:25,631] vagrant-ubuntu-trusty-64/ERROR/stderr: File "/usr/local/lib/python3.4/dist-packages/gevent-1.1.0-py3.4-linux-x86_64.egg/gevent/event.py", line 101, in _wait_core
[2016-03-30 04:01:25,632] vagrant-ubuntu-trusty-64/ERROR/stderr: 
[2016-03-30 04:01:25,632] vagrant-ubuntu-trusty-64/ERROR/stderr: result = self.hub.switch()
[2016-03-30 04:01:25,632] vagrant-ubuntu-trusty-64/ERROR/stderr: 
[2016-03-30 04:01:25,632] vagrant-ubuntu-trusty-64/ERROR/stderr: File "/usr/local/lib/python3.4/dist-packages/gevent-1.1.0-py3.4-linux-x86_64.egg/gevent/hub.py", line 606, in switch
[2016-03-30 04:01:25,633] vagrant-ubuntu-trusty-64/ERROR/stderr: 
[2016-03-30 04:01:25,633] vagrant-ubuntu-trusty-64/ERROR/stderr: return greenlet.switch(self)
[2016-03-30 04:01:25,633] vagrant-ubuntu-trusty-64/ERROR/stderr: 
[2016-03-30 04:01:25,634] vagrant-ubuntu-trusty-64/ERROR/stderr: gevent.hub
[2016-03-30 04:01:25,634] vagrant-ubuntu-trusty-64/ERROR/stderr: .
[2016-03-30 04:01:25,635] vagrant-ubuntu-trusty-64/ERROR/stderr: LoopExit
[2016-03-30 04:01:25,635] vagrant-ubuntu-trusty-64/ERROR/stderr: :
[2016-03-30 04:01:25,635] vagrant-ubuntu-trusty-64/ERROR/stderr: ('This operation would block forever', <Hub at 0x7fcb7a9e9800 epoll default pending=0 ref=0 fileno=4 resolver=<gevent.resolver_thread.Resolver at 0x7fcb7778f780 pool=<ThreadPool at 0x7fcb7778f7b8 0/1/10>> threadpool=<ThreadPool at 0x7fcb7778f7b8 0/1/10>>)
[2016-03-30 04:01:25,636] vagrant-ubuntu-trusty-64/ERROR/stderr: 
```

**Comment by alexandrul** [comment]
gevent 1.1.1 supports 3.5, even having wheels for windows :+1: 

https://pypi.python.org/pypi/gevent

**Comment by deniscostadsc** [comment]
Hey guys,

I'd like to help to have this PR merged. What are the steps we should take in order to have that? I can work on it!

**Comment by justiniso** [comment]
@deniscostadsc the only blocking issue I have right now is: https://github.com/locustio/locust/pull/363#issuecomment-203714951

Repro is to start up a master and slave instance on the branch. I was using python 3.5 on ubuntu 14.04 and python 3.5 on osx el capitan.

**Comment by deniscostadsc** [comment]
@justiniso I'd appreciate if you could solve the conflicts on your fork, so I can take a look on it.

**Comment by cgoldberg** [comment]
@justiniso 
is changing flush() to a no-op a good idea?  I'm wondering if your change will cause some logging output to get lost (if the program exits without flushing the log buffers).  Rather than a no-op, can we actually flush the buffer when it gets called?

**Comment by mtraynham** [comment]
I'd also like to know if this still has traction behind it.  Can someone advise on a timeframe for fixing the comment above, merge and release?  Is it just the gevent upgrade preventing the merge?

**Comment by justiniso** [comment]
@mtraynham there is absolutely still traction behind this. Currently the only blocking issue is the gevent upgrade but that's blocking further testing which might surface other issues. We can't give you an ETA, but if you have familiarity with gevent, any PR or advice would be appreciated.

**Comment by justiniso** [comment]
I've pushed a branch that would fix the ["This operation would block forever"](https://github.com/locustio/locust/pull/363#issuecomment-203714951) issue above. Turns out a standard install on a fresh vm made with the Vagrantfile does not install pyzmq. So it was not using the green thread implementation of zmq. 

The branch is here: https://github.com/locustio/locust/commits/python3-justiniso. @pmdarrow can you merge that branch into yours so we can keep discussion here without having to open another pull request? 

*side note: anyone at pycon in portland right now?

**Comment by heyman** [comment]
@justiniso Great! Do you know of any other existing issues before this could be merged?

Not at Pycon unfortunately. Next year hopefully :).

**Comment by heyman** [comment]
Hmm, perhaps I'm misinterpreting the Travis UI, but it looks like it's only running Python 3.5 in each build job:

image
image

**Comment by deniscostadsc** [comment]
On [travis.yml](https://github.com/locustio/locust/blob/python3-justiniso/.travis.yml) just version 3.5 of Python is declared

But maybe, tox is dealing with this in the correct way, creating all venvs. But you won't be able to see it on Travis UI.

Why not creating a matrix on Travis instead of using tox? Do you want to run all possibilities locally?

**Comment by heyman** [comment]
Ah, yes, tox takes care of picking the correct version. And I guess the ability to easily run tests for all versions is convenient.

**Comment by pmdarrow** [comment]
@deniscostadsc you are correct, tox (running under Python 3.5) is creating all the venvs for each version of Python we want to support. And you are also correct, it lets devs test against all supported versions of Python locally.

**Comment by pmdarrow** [comment]
@justiniso I cherry-picked your commit to explicitly declare pyzmq. Are people still experiencing issues with gevent or was that resolved with gevent 1.1.1?

**Comment by justiniso** [comment]
> Are people still experiencing issues with gevent or was that resolved with gevent 1.1.1

@pmdarrow if you're referring to my issue with gevent, that is fixed by the commit you just cherry-picked. If there are other issues, I'm not aware of them. My testing has been on linux and osx (unfortunately don't have a Windows machine to test with). As far as I'm aware, there are no other issues preventing merge.

**Comment by pmdarrow** [comment]
@justiniso Ok. What should we do about releasing a new version of Locust? I'm guessing none of us "new" contributors have access to https://pypi.python.org/pypi/locustio?

**Comment by justiniso** [comment]
Right, @heyman would have to do that. I would go with versioning as a pre-release 0.8a1 to flag as a potentially unstable version. It would be nice to let it soak with early adopters and let them report any issues with integrations, etc. before fully rolling it out.

**Comment by pmdarrow** [comment]
I'll merge this and then create another PR with the release changes, if this looks good to you?

**Comment by justiniso** [comment]
🙌

**Comment by Slach** [comment]
:raised_hands:
hooray ! ;)

**Comment by heyman** [comment]
Woho, great work!

It sounds like a good idea to do a pre-release alpha first.

**Comment by dlai0001** [comment]
👏  Awesome guys.  Looking forward to using this in py3

**Comment by cgoldberg** [comment]
nice!

**Comment by ryankennedyio** [comment]
Great work. Would be great to get this on pypi as it would help the automation process quite a bit.

**Comment by heyman** [comment]
@ryankennedyio The latest master has been released to PyPI as a pre release, and can be installed by specifying the version explicitly (`0.8a1`)

**Comment by baynes** [comment]
When will it come the main release rather than pre-release?
Or how about correcting the installation instructions on the website?

**Pull request merged**
