### PR TITLE
Ability to control the Locust process' exit code

### PR DESCRIPTION
**Pull request by heyman**
PR for #587

### CODE REVIEW

**Comment by cyberw** [comment]
Looks good! Could you add an example on how to set the return code based on rps or avg response time as well?

**Comment by heyman** [comment]
I've extended the example to also check for average response time as well as response time percentile. 

I'm hesitant on adding an RPS check to the example because I think it's a slightly weird condition to use (since it's very dependent on both the number of simulated users as well the actual code of the User classes). It shouldn't be hard to figure out for anyone who still wants to do it, but I don't think it should be encouraged by an example in the official docs.

> And maybe do a log entry in the example as well.

Good idea!

**Comment by cyberw** [comment]
Ok to merge! I still think an RPS check is a good idea, especially for CI purposes. Yes, RPS depends on your test plan, but that is constant over CI runs. There are cases where RPS might drop even though response times do not rise (e.g. delays reading test data, load gen overload etc) which you would definitely want to catch. 

But if you are -1 on that, I can just comment it in the ticket (which was about RPS, just like the slack question that made me reopen it :)

**Comment by cyberw** [comment]
Lets worry about (possibly) adding rps thresholds to the documentation later. Merging.

**Pull request merged**
