### PR TITLE
Adds support for setup, teardown, and on_stop methods

### PR DESCRIPTION
**Pull request by DeepHorizons**
If a TaskSet has an `on_stop` method, it will be run before the process exits. It will also look for a property on the class named `always_run_on_stop`, which if True will run regardless if the `on_start` method finished.

Looking to solve #59 

Any comments on this functionality?

### CODE REVIEW

**Comment by heyman** [comment]
Hi! I've looked through the changes and here are my initial thoughts:

The `on_start` method of a TaskSet is run every time a Locust "enters" that TaskSet which might be many times during a test run (since it's common to have nested TaskSets). I do think it could be a good idea to add the ability to have an `on_stop` method on TaskSets, but then I think it should run within the Locust greenlet whenever a TaskSet is interrupted (so that on_stop is symmetrically opposite to on_start).

If we want to provide some hook that is executed for each Locust user when a test is stopped, I think it should be a method under the Locust class, and I also think it should be executed within the Locust greenlet (by catching GreenletExit, and we need to make sure that the greenlets are actually killed properly when running locust locally with `--no-web` and pressing CTRL-C).

**Comment by DeepHorizons** [comment]
That makes way more sense than what I was thinking/doing. `on_stop` should be a one to one with `on_start`, while the setup and teardown should be just once.

I re-worked the Locust run method to catch that exception, then run `on_stop` if it exists.  I also added the `locust_runner.quit()` during shutdown which should clean up those greenlets. I'm not sure if you use them anywhere else though.

Here is my idea for the setup and teardown. The Locust class and the TaskSet class can have a `setup` and `teardown` method. They will be class methods, not tied to any particular instance. There will also be some class variable to hold the state to see if they have been run already. Order of running would be `setup` on Locust, `setup` on TaskSet, `teardown` on TaskSet, `teardown` on Locust. The `__init__` methods will be modified to check to see if the `setup` method have been run. If not, run them and update the state. As for the teardown, I'll probably do something similar to what I was doing adding a handler to the `quitting` event.

**Comment by j616** [comment]
I just thought I'd feed back that I've been using this branch for a few weeks for the `on_stop` functionality in task sets. It works exactly as I'd expect it to and feels almost essential for allowing my locustfiles to clean up after themselves. Hoping this get's accepted into the main upstream. It's too useful to just sit in someone's fork. Thanks for putting in the dev work, @DeepHorizons

**Comment by DeepHorizons** [comment]
@j616 Thanks for letting me know! Let me add some documentation, then I'll remove the [WIP]

**Comment by swordmaster2k** [comment]
I'm also actively using the functionality provided by this branch, the on_stop functions exactly how I'd expect it to. I have a websocket associated with each locust running on their on greenlets so I needed some way to close the websockets when the controlling locust was stopped. This branch provides that ability, would be nice to see it merged into the official branch.

**Comment by aldenpeterson-wf** [comment]
this LGTM.

@heyman @cgbystrom @mbeacom any of you have thoughts on this? It'd be nice to get this into the 0.9.0 release.

**Comment by mbeacom** [comment]
@aldenpeterson-wf Unless there are any objections, lgtm.  We'll wait a little and if no one speaks up, maybe merge it this week?

**Comment by cgoldberg** [comment]
sure.. might as well be consistent

**Comment by cgoldberg** [comment]
@DeepHorizons thanks for the contribution!

**Comment by aldenpeterson-wf** [comment]
@heyman you want to cut another release? This is pretty great functionality and combined with the time based run worthy of releasing imo.

**Comment by cgoldberg** [comment]
+1 for release.  We also need to add a nice description of this to `/docs/changelog.rst`.

**Comment by migueleliasweb** [comment]
**Waiting anxiously**

**Comment by migueleliasweb** [comment]
@cgoldberg How's things ? Do you think that it will take long before releasing this ?

**Comment by cgoldberg** [comment]
@migueleliasweb 
we are going to cut a release candidate (hopefully soon) ... but not sure the timeline yet for the official 0.9 release.

**Comment by heyman** [comment]
Hey! I realize that this comment is way late, but as far as I can tell from the code, the setup/teardown will run multiple times when running Locust distributed. I think we either need to make sure this is not the case (perhaps by only running the setup & teardown in the master node), or at least update the documentation which currently states that the setup/teardown is run only once. Though I think it's much preferable if Locust works the same wether it's being run distributed or not.

**Comment by stefanbie** [comment]
As far as I can tell Locust teardown is not working in 0.9.0.

**Comment by stefanbie** [comment]
Sorry, I was wrong, it actually works, great work guys!!! :)

**Comment by AbigailMcP** [comment]
@stefanbie - I'm having trouble getting Locust teardown to work in 0.9.0 (it doesn't appear to run at all?) could you share your solution?

**Pull request merged**
