### PR TITLE
Update change logs & release 0.10.0

### PR DESCRIPTION
**Pull request by aldenpeterson-wf**
Should be more straightforward this time.

The auto changelog reordered some things but left them all present.

@cgbystrom @heyman @cgoldberg

### CODE REVIEW

**Comment by jmirc** [comment]
When do you plan to release

**Comment by aldenpeterson-wf** [comment]
@jmirc sometime in 2019, most likely.

**Comment by jmirc** [comment]
We are using locust with kubernetes and we are interesting by the "Add heartbeat to detect down slaves" feature. Do you have a doc to create a release on our side? We could be able to push it inside a private docker repository

**Comment by aldenpeterson-wf** [comment]
My comment was perhaps a bit sarcastic but realistically, once someone with pypi push credentials reviews this and tags as needed  (I don't have these creds or I would).

Release process is documented here - https://github.com/locustio/locust/blob/master/.github/CONTRIBUTING.md

**Pull request merged**
