### PR TITLE
Add charts for RPS and average response time in the WebUI

### PR DESCRIPTION
**Pull request by myzhan**
Keeping trace of test results by charts

### CODE REVIEW

**Comment by decklord** [comment]
This feature would be awesome. Can you merge this guys?

**Comment by Slach** [comment]
+1 please merge this feature to upstream!

**Comment by cgoldberg** [comment]
@myzhan 
can we separate this into 2 PR's to get them reviewed individually:
 1. JS charts
 2. Boomer

**Comment by myzhan** [comment]
@cgoldberg, ok, I can submit a new PR later.

**Comment by cgoldberg** [comment]
@myzhan thanks!  please tag me as a reviewer for each

**Pull request closed without merging**
