### PR TITLE
bugfix fail_ratio calculation error

### PR DESCRIPTION
**Pull request by solxnp**

### CODE REVIEW

**Comment by cyberw** [comment]
image

num_requests contains both failures and successes, so the current behaviour is correct (except in the case you are experiencing :) applying this change would count failures twice.

**Comment by cyberw** [comment]
It is really weird that neither the current version nor the suggested change fails any unit tests though. We should add such a test.

**Comment by cyberw** [comment]
Actually, your suggested change fails the tests, but for some reason no builds were executed. Weird.

**Comment by solxnp** [comment]
I think I know what the problem is
thanks

**Pull request closed without merging**
