### PR TITLE
Update third-party-tools.rst

### PR DESCRIPTION
**Pull request by anhldbk**
Added Java Locust Swarm client

### CODE REVIEW

**Comment by anhldbk** [comment]
@ps-george I'm sorry. What do you think about the idea of grouping clients based on their languages? If we don't need that, then I add another heading for my client

**Comment by ps-george** [comment]
I think it's a good idea to group clients by languages :+1:

**Comment by anhldbk** [comment]
@ps-george ps I updated

**Comment by aldenpeterson-wf** [comment]
LGTM

**Pull request merged**
