### PR TITLE
Allow worker process to run with --run-time specified, just log a warning

### PR DESCRIPTION
**Pull request by Sawiq**
As discussed [here](https://github.com/locustio/locust/issues/2683)

### CODE REVIEW

**Comment by cyberw** [comment]
Looks good apart from the type check fail (which probably isnt really your fault, but still needs to be fixed)

**Comment by tdadela** [comment]
```py
    parts = timespan_regex.match(time_str)
    if not parts:
        raise ValueError("Invalid time span format. Valid formats: 20, 20s, 3m, 2h, 1h20m, 3h30m10s, etc.")
    parts = parts.groupdict()
```
The same variable name is used for storing two different types.
One of solutions is simply to rename **parts** variable.

Before this PR def parse_timespan(time_str): was untyped so mypy was skipping checking it: 
- "note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs"
- https://github.com/locustio/locust/blob/ca33b58ba9938c0ad68f9f2c9070da1da18b6c0a/pyproject.toml#L104

**Comment by cyberw** [comment]
Yes that looks terrible. Renaming makes sense I think!

**Comment by Sawiq** [comment]
I have removed reassignment and called `groupdict` inline within list comprehension.

**Pull request merged**
